#!/bin/bash

################################################################################
#    Copyright (c) 2012, KAIST.
#    All rights reserved.
#
#    Use is subject to license terms.
#
#    This distribution may include materials developed by third parties.
################################################################################

find_ant(){
  # Strip "." from the path, and look for ant.
  # This avoids infinite regress if this is the first or only "ant" on the normal PATH.
  export NODOTPATH="`echo "$PATH" | sed -e '1,$s/^[.]://g'`"
  NODOTPATH="`echo "$NODOTPATH" | sed -e '1,$s/:[.]:/:/g'`"
  NODOTPATH="`echo "$NODOTPATH" | sed -e '1,$s/:[.]$//g'`"
  result="`(PATH="$NODOTPATH" which ant 2>/dev/null)`"
  if [ -z "$result" ]; then
    echo "Could not find ant. You need to install it. See http://ant.apache.org/ for details." >&2
    exit 1
  fi
 echo $result
 exit 0
}

ant_exec="`find_ant`"
n=$?
if [ $n -ne 0 ]; then
        exit $n
fi

# Note that the scripts reference must export their symbols so that they are available below.
. ./antrc_suggested

"$ant_exec" -noclasspath "$@"
