var json_ua=null,form_tk=document.getElementsByName("rds_form_token")[0]&&document.getElementsByName("rds_form_token")[0].value||"";"undefined"==typeof alipay&&(alipay={});alipay.auth||(alipay.auth={});
alipay.auth.checkcode=function(a){this.init();for(var b in a)this[b]=a[b];document.getElementsByName("logonIdReadOnly")[0]&&document.getElementsByName("logonIdReadOnly")[0].value=="true"&&this.failCallback.call(this);if(!this.form||!this.logonId||!this.errorBox||!json_ua)this.failCallback.call(this);else{this.logonIdFirstValue=this.logonId.node.value;this.supportAliedit()||this.showCheckCode();this.bind()}};
alipay.auth.checkcode.prototype={form:null,logonId:null,logonIdFirstValue:null,errorBox:null,accountFormatError:["\u8bf7\u8f93\u5165\u8d26\u6237\u540d\u3002","\u5e10\u6237\u540d\u7684\u957f\u5ea6\u4e0d\u80fd\u8d85\u8fc7100\u4f4d\u3002","\u652f\u4ed8\u5b9d\u8d26\u6237\u662f\u90ae\u7bb1\u5730\u5740\u6216\u624b\u673a\u53f7\u7801\u3002"],accountSwtich:!0,accountInfoShow:!1,accountInfoNode:null,isAlertType:!1,accountsaverKey:null,codeCnt_:null,authcode:null,formSubmit_:null,formToken:null,isPerson:!1,
timer:null,timeout:3E3,accountValue:null,accountResult:!1,accountErrorCode:null,accountTips:window.ACCOUNTTIPS,ajaxTarget:null,init:function(){this.form=$("login")&&$("login").node;this.logonId=$("logonId");this.errorBox=$("error-box");this.codeCnt_=$$(".sl-checkcode")[0].node;this.authcode=$$(".sl-checkcode input[name=checkCode]")[0];this.formToken=$$("input[name=rds_form_token]",$(this.form))[0]},bind:function(){var a=this;this.submitAspect();a.form&&E.connect($(a.form),"onclick",a,function(b){b=
b.target;b.id=="safeSignCheck"&&(b.checked?a.isPerson&&a.hideCheckCode():a.failCallback.call(a))});(!a.logonId||!a.logonId.node.id||!a.codeCnt_||a.codeCnt_&&a.codeCnt_.style.display=="block")&&a.failCallback.call(a);setTimeout(function(){try{(a.isLogonIdFocus=true)&&a.logonId.node.focus()}catch(b){a.failCallback.call(a)}},300);E.connect(a.logonId,"onblur",function(){a.isLogonIdFocus&&(a.checkAccount(a.logonId.attr("value"))?a.request():a.sendSeed("accounterror"))})},checkAccount:function(a){a.replace(/^\s+|\s+$/g,
"");a=a.replace(/^\s+|\s+$/g,"");a.replace(/[\u3002\uff0e]/,".");a=a.replace(/[\u3002\uff0e]/,".");if(a.length==0||a===this.logonId.attr("placeholder"))return false;if(a.length>100){this.showErrorBox(this.accountFormatError[1]);return false}if(!this.emailOrMobile(a)){this.showErrorBox(this.accountFormatError[2]);return false}return true},emailOrMobile:function(a){var b=false;/^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/.test(a)?b=true:/^1\d{10}$/.test(a)?b=true:/^(00)?(886|853|852|82|81|65|60)[0-9]{8}$/.test(a)?
b=true:/^(00)?(886|853|852|82|81|65|60)-?[0-9]{7,11}$/.test(a)&&(b=true);return b},insertFormToken:function(){var a=this.formToken;if(!a){a=document.createElement("input");a.setAttribute("type","hidden");a.name="rds_form_token";a.value=form_tk;this.form.appendChild(a)}},supportAliedit:function(){return document.getElementsByName("J_aliedit_using")[0]&&document.getElementsByName("J_aliedit_using")[0].value==="true"},submitAspect:function(){var a=this.form.submit,b=this;this.form.submit=function(){b.insertFormToken();
b.onSubmit&&b.onSubmit.call(b);b.formSubmit_=a;if(!b.accountSwtich||b.accountSwtich&&b.accountResult){try{system.auth.accountsaver.save(b.accountsaverKey)}catch(e){}try{a()}catch(h){a.call(b.form)}}else b.accountErrorCode?b.showErrorBox(b.accountTips[b.accountErrorCode]):b.accountValue==null?b.checkAccount(b.logonId.attr("value"))&&b.request():b.sendSeed("onSubmit-others")}},sendSeed:function(a){typeof Tracker!="undefined"&&Tracker.click(a)},reset:function(){this.accountErrorCode=this.accountValue=
this.formSubmit_=null;this.accountResult=false},showCheckCode:function(){this.codeCnt_.style.display="block";this.sendSeed("authlogin-showCheckCode-"+window.location.hostname.split(".")[0])},hideCheckCode:function(){this.codeCnt_.style.display="none";this.authcode.node.value="";if($("checkcodeIcon")){$("checkcodeIcon").removeClass("checkcodeIcon-wrong");$("checkcodeIcon").removeClass("checkcodeIcon-right")}},request:function(){var a=this,b=a.errorBox.attr("errorType");b=="0"&&a.logonId.attr("value")!=
a.logonIdFirstValue&&a.hideErrorBox();b=="1"&&A(a.accountFormatError).indexOf(a.errorBox[0].innerHTML)!=-1&&(a.accountErrorCode?a.showErrorBox(a.accountTips[a.accountErrorCode]):a.hideErrorBox());if(a.logonId.attr("value")!=a.accountValue){b=="1"&&a.hideErrorBox();a.reset();a.accountValue=a.logonId.attr("value");Loader.use("arale.http",function(){var b={},b=a.accountInfoShow?{logonId:a.accountValue,_json_token:form_tk,json_ua:json_ua,sceneCode:"AC1",stamp:(new Date).getTime(),getUser:true}:{logonId:a.accountValue,
_json_token:form_tk,json_ua:json_ua,sceneCode:"AC1",stamp:(new Date).getTime()};a.ajaxTarget=Ajax.post("/login/verifyId.json",{success:function(b){a.successCallback.call(a,b)},timeout:a.timeout,failure:function(){a.failCallback.call(a);a.accountResult=true},data:b})})}},successCallback:function(a){if(a.isPerson=="true")this.isPerson=true;else{this.showCheckCode();this.accountInfoShow&&this.clearAccountInfo();this.onFailCallback&&this.onFailCallback.call(this,a)}if(this.accountSwtich)if(this.accountTips[a.checkResult]){clearTimeout(this.timer);
this.accountResult=false;this.accountErrorCode=a.checkResult;this.accountInfoShow&&this.clearAccountInfo();this.showErrorBox(this.accountTips[this.accountErrorCode])}else{this.accountResult=true;if(this.accountInfoShow&&a.enabledStatus)if(a.enabledStatus==="T")this.showAccountInfo(a);else if(a.enabledStatus==="Q"){this.clearAccountInfo();clearTimeout(this.timer);this.showErrorBox(this.accountTips.STATUS_NEED_ACTIVATE)}}if(this.formSubmit_&&this.isPerson&&(!this.accountSwtich||this.accountSwtich&&
this.accountResult)){try{system.auth.accountsaver.save(this.accountsaverKey)}catch(b){}try{this.formSubmit_()}catch(e){this.formSubmit_.call(this.form)}}this.ajaxTarget=null},failCallback:function(){this.showCheckCode();this.onFailCallback&&this.onFailCallback.call(this,null);this.ajaxTarget=null},showErrorBox:function(a){if(!this.isAlertType){this.errorBox.node.innerHTML=a;this.errorBox.removeClass("fn-hide");this.errorBox.attr("errorType","1");this.onFailCallback&&this.onFailCallback.call(this,
null)}},hideErrorBox:function(){var a=this;clearTimeout(a.timer);a.timer=setTimeout(function(){a.errorBox.node.innerHTML="";a.errorBox.addClass("fn-hide");a.errorBox.attr("errorType","")},500)},showAccountInfo:function(a){if(typeof a.realName!=="undefined"&&typeof a.bindMobile!=="undefined"){$("J-getAccount").removeClass("fn-hide");$("J-getAccount-result").removeClass("fn-hide");$("J-showRealName").setHtml(a.realName);$("J-showMobile").setHtml(a.bindMobile)}},clearAccountInfo:function(){$("J-getAccount").addClass("fn-hide");
$("J-getAccount-result").addClass("fn-hide");$("J-showRealName").setHtml("");$("J-showMobile").setHtml("")}};
(function(a){if(a){var b=function(a,b,f){for(var c=0,e=a.length;c<e;c++)b.call(f||null,a[c])},e=function(i,d){b(i,function(b){var i=a[b];a[b]=function(){d(i,arguments)}})},h={callbacks:{},publish:function(a,d){this.callbacks[a]&&b(this.callbacks[a],function(a){a.apply(null,d)})},subscibe:function(a,b){this.callbacks[a]||(this.callbacks[a]=[]);this.callbacks[a].push(b)}};a.register=function(b){var d=false;e(["use","waituse"],function(b,c){d?b.apply(a,c):h.subscibe("Loader/register/use",function(){b.apply(a,
c)})});for(var f=araleConfig.combo_host+araleConfig.combo_path,c=[],k=b.length,j=0;j<k;j++){var g=b[j];araleConfig.combo_path.indexOf("ar")==-1&&(g.indexOf("alipay")!=-1||g.indexOf("arale")!=-1)?c.push("/static/"+g):c.push(g)}f=f+c.join("-index.js,");a.loadScriptByUrl(f+"-index.js",function(){d=true;h.publish("Loader/register/use",[])})}}})(Loader);