(function(a){var b=a.document,d=a.location,g=Array.prototype,k,e;try{e=d.href}catch(c){e=b.createElement("a"),e.href="",e=e.href}k=/^([\w\+\.\-]+:)(?:\/\/([^\/?#:]*)(?::(\d+))?([^?#]*))?/.exec(e.toLowerCase())||[];var i={version:"0.1",timestamp:(new Date).getTime(),debug:-1===k[2].indexOf("alipay.com"),baseDomain:function(){var f=k[2].split(".");return f.slice(-Math.max(f.length-1,2)).join(".")}(),urlParts:k,toString:function(){var f="Light JavaScript Library version "+i.version;i.debug&&(f+=", debug enabled");
return f+"."},toArray:function(f){return g.slice.apply(f)},map:function(f,a,m){if(g.map)return g.map.call(f,a,m);var h=[],c=f.length;if(!c)return h;for(var b=0;b<c;b++)h[b]=a.call(m,f[b],b,f);return h},reduce:function(f,a,b){if(g.reduce)return g.reduce.call(f,a,b);var h=0,c=f.length;if(!c&&void 0==b)throw new TypeError("Reduce of empty array with no initial value");void 0==b&&(b=f[0],h=1);for(;h<c;)b=a.call(void 0,b,f[h],h,f),h++;return b},register:function(f,j,b){f=f.split("/");j=j||i;f[0]||(j=a,
f.shift());for(var h,c=0,g=f.length-1;c<g;c++)if(h=f[c])j=j[h]=j[h]||{};(h=f[c])&&(j=j[h]=void 0===b?{}:b);return j},extend:function(f){var a=i.toArray(arguments);"boolean"!==typeof a[0]&&a.unshift(f=!1);if(2>a.length)return null;var b=2,h=a[1];2===a.length&&(b=1,h=i);for(var c=b,g=a.length;c<g;c++)if((b=a[c])&&"object"===typeof b)for(var e in b){var d=b[e];d!==h&&b.hasOwnProperty(e)&&(i.isArray(d)?h[e]=Array.prototype.concat.call(d):f&&d instanceof Object&&!i.isFunction(d)&&!d.nodeType?h[e]=i.extend(!0,
h[e]||{},b[e]):void 0!==d&&(h[e]=d))}return h},deriveFrom:function(f,a,b){if(2>arguments.length)return f;var c=a&&a.init||function(){f.constructor.apply(this,arguments)};i.extend(!0,c.prototype,f.prototype,a);c.constructor=c;b&&i.extend(!0,c,b);c.__super=f;return c},module:function(f,a){var b=i.register(f,null,a);i.isFunction(a)&&(b.constructor=a);return b},each:function(a,b){if(!a)return a;var c=a.length;if(void 0!==c&&"reverse"in a)for(var h=0;h<c&&!1!==b.call(a[h],h,a[h],a);)h++;else for(h in a)if(!1===
b.call(a[h],h,a[h],a))break;return a},isFunction:function(a){return"function"===i.type(a)},isArray:Array.isArray||function(a){return"array"===i.type(a)},isString:function(a){return"string"===i.type(a)},isObject:function(a){return"object"===i.type(a)},isNull:function(a){return"null"===i.type(a)},isUndefined:function(a){return void 0===a},isWindow:function(a){return a&&"object"===typeof a&&"setInterval"in a},type:function(a){return null===a||void 0===a?""+a:l[Object.prototype.toString.call(a)]||"object"},
has:function(b){if(!b)return!1;var b=b.split("/"),c=i,e,h;b[0]||(c=a,b.shift());e=0;for(h=b.length;e<h;e++)if(c=c[b[e]],void 0===c)return!1;return!0},noop:function(){}},l={};i.each("Boolean,Number,String,Function,Array,Date,RegExp,Object,Null".split(","),function(a,b){l["[object "+b+"]"]=b.toLowerCase()});a.light=i})(window);
light.extend({log:function(){return!light.debug||!window.console||!console.log?function(){if(light.debug)try{window.console&&console.log&&console.log.apply(console,arguments)}catch(a){}}:Function.prototype.bind?function(){light.debug&&Function.prototype.bind.call(console.log,console).apply(console,arguments)}:console.log.apply?function(){light.debug&&console.log.apply(console,arguments)}:light.debug?console.log:light.noop}(),inspect:function(a){var b=function(a){if(!light.isObject(a))return light.isString(a)?
'"'+a+'"':a.toString();var d=[],e;for(e in a)light.isUndefined(a[e])||(light.isNull(a[e])?d.push('"'+e+'":null'):light.isObject(a[e])?d.push('"'+e+'":{'+b(a[e])+"}"):d.push('"'+e+'":'+b(a[e])));return d.join()};if(window.JSON&&JSON.stringify)return JSON.stringify(a);if("object"===typeof a){var d="",d=b(a);return"{"+d+"}"}return""+a},track:function(){var a=[],b=function(d){window.Tracker?Tracker.click(d):(a.push(d),window.setTimeout(function(){b(a.shift())},100))};return function(a,g){if(a){if(g)var k=
light.client.info,e=k.browser.version,e=e?e[0]:"na",a=a+("-"+(k.browser.name||"na")+"-"+(k.engine.name||"na")+"-"+e);b(a)}}}(),trim:function(a){return!a?"":String.prototype.trim?String.prototype.trim.apply(a):a.replace(/^\s+|\s+$/g,"")},substitute:function(a,b,d){if(!a)return"";if(!b)return a;if("string"!==typeof a)throw"invalid template";return a.replace(RegExp("{\\w+}","gmi"),function(a){a=a.substr(1,a.length-2);return a in b?b[a].toString():d?"{"+a+"}":""})},encode:encodeURIComponent||escape,decode:decodeURIComponent||
unescape,param:function(a,b,d){var b=b||"=",g=[];light.each(a,function(d,e){d&&a.hasOwnProperty(d)&&g.push(light.encode(d)+b+light.encode(e))});return g.join(d||"&")},unparam:function(a,b,d){var g={};if(!a)return g;b=b||"=";light.each(a.split(d||"&"),function(a,e){var c=e.split(b,2);c[0]&&2===c.length&&(g[light.decode(c[0])]=light.decode(c[1]))});return g},trimTag:function(a){if(!a||!document.createElement)return"";var b=document.createElement("DIV");b.innerHTML=a;return b.textContent||b.innerText||
""},escapeHTML:function(a){if(!a)return"";a=a.replace(/>/g,"&gt;");a=a.replace(/</g,"&lt;");a=a.replace(/&/g,"&amp;");a=a.replace(/"/g,"&quot;");return a=a.replace(/'/g,"&#039;")},unescapeHTML:function(a){if(!a)return"";a=a.replace(/&gt;/g,">");a=a.replace(/&lt;/g,"<");a=a.replace(/&amp;/g,"&");a=a.replace(/&quot;/g,'"');return a=a.replace(/&#039;/g,"'")},toJSON:function(a){if("string"!==typeof a||!a)return null;a=light.trim(a);return window.JSON&&JSON.parse?JSON.parse(a):(new Function("return "+
a))()}});(function(){var a=function(){this.stack=[];var a=this,d=[].slice.call(arguments,0);d&&light.each(d,function(d){a.add(d)})};a.prototype={add:function(a){this.stack.push(a)},clear:function(){this.stack=[]},invoke:function(){var a=this,d=[].slice.call(arguments,0);fn=this.stack.shift();this.next||(this.next=function(){a.stack.length&&a.invoke.apply(a,d)});fn.apply(null,[this.next].concat(d))}};light.queue=a})();
(function(a,b){var d=a.document,g=a.navigator,k=g.userAgent?g.userAgent.toLowerCase():"",e=a.external,g={device:{pc:"windows",ipad:"ipad",ipod:"ipod",iphone:"iphone",mac:"macintosh",android:"android",nokia:/nokia([^\/ ]+)/},os:{windows:/windows nt (\d)\.(\d)/,macos:/mac os x (\d+)[\._](\d+)(?:[\._](\d+))?/,linux:"linux",ios:/iphone os (\d)[\._](\d)/,android:/android (\d)\.(\d)/,chromeos:/cros i686 (\d+)\.(\d+)(?:\.(\d+))?/,windowsce:0<k.indexOf("windows ce ")?/windows ce (\d)\.(\d)/:"windows ce",
symbian:/symbianos\/(\d+)\.(\d+)/,blackberry:"blackberry"},engine:{trident:/msie (\d+)\.(\d)/,webkit:/applewebkit\/(\d+)\.(\d+)/,gecko:/gecko\/(\d+)/,presto:/presto\/(\d+).(\d+)/},browser:{360:function(){if(!c.os.windows)return!1;if(e)try{return e.twGetVersion(e.twGetSecurityID(a)).split(".")}catch(b){try{return-1!==e.twGetRunPath.toLowerCase().indexOf("360se")||!!e.twGetSecurityID(a)}catch(d){}}return/360(?:se|chrome)/},mx:function(){if(!c.os.windows)return!1;if(e)try{return(e.mxVersion||e.max_version).split(".")}catch(a){}return-1!==
k.indexOf("maxthon ")?/maxthon (\d)\.(\d)/:"maxthon"},sg:/ se (\d)\./,tw:function(){if(!c.os.windows)return!1;if(e)try{return-1!==e.twGetRunPath.toLowerCase().indexOf("theworld")}catch(a){}return"theworld"},qq:function(){return 0<k.indexOf("qqbrowser/")?/qqbrowser\/(\d+)\.(\d+)\.(\d+)(?:\.(\d+))?/:/tencenttraveler (\d)\.(\d)/},ie:0<k.indexOf("trident/")?/trident\/(\d+)\.(\d+)/:/msie (\d+)\.(\d+)/,chrome:/chrome\/(\d+)\.(\d+)\.(\d+)(?:\.([ab\d]+))?/,safari:/version\/(\d+)\.(\d+)(?:\.([ab\d]+))? safari\//,
firefox:/firefox\/(\d+)\.([ab\d]+)/,opera:/opera.+version\/(\d+)\.([ab\d]+)/},feature:{"64bitBrowser":"win64; x64;","64bitOS":/win64|wow64/,security:/ (i|u|s|sv1)[;\)]/,simulator:function(){return c.os.ios&&960<screen.width}}},c={};b.each(g,function(a,e){c["has"+a.charAt(0).toUpperCase()+a.slice(1)]=function(b,e){var f;a:if(!c[a]||!(f=c[a][b]))f=!1;else{if(e){var d=e;"string"===typeof d?d=d.split("."):"number"===typeof d&&(d=[d]);for(var g,k,l=0,n=Math.max(d.length,f.length);l<n;l++)if(g=parseInt(d[l],
10)||0,k=parseInt(f[l],10)||0,g!==k){f=g<k;break a}}f=!0}return f};var f=c[a]={};b.each(e,function(a,e){var d=[0],g=b.isFunction(e)?e.apply(c):e;if(g)if(!0===g)d=[-1];else if("string"===typeof g)d=[-1!==k.indexOf(g)?-1:0];else{var i=g;g.exec&&(i=g.exec(k)||[],i.length&&i.shift());for(g=0;g<i.length;g++)d[g]=parseInt(i[g],10)||0}if(i=!!d[0])f[a]=f.version=d,f.name=a;return!i})});!c.engine.name&&a.ActiveXObject?(d.documentMode?c.engine.trident=c.engine.version=[d.documentMode,0]:c.engine.trident||(c.engine.trident=
c.engine.version=[-1]),c.engine.name="trident"):!c.os.windows&&c.hasEngine("trident",6)&&(c.os.windows=c.os.version=[-1],c.os.name="windows");c.browser.ie&&0<k.indexOf("trident/")&&(c.browser.ie[0]=c.browser.version[0]+=4);b.module("client/info",c)})(window,light);
(function(a,b){var d=a.document,g=a.navigator,k=!1,e=function(){k||(b.write('<input type="hidden" id="__ud" style="behavior:url("#default#userData")"/>'),k=!0);return b.get("__ud")},c={cookie:null,defaultStorage:a.localStorage,set:function(a,f){if(c.cookie&&g.cookieEnabled){var j=a+"="+encodeURIComponent(f);if(c.cookie.days)var k=new Date((new Date).getTime()+864E5*c.cookie.days),j=j+("; expires="+k.toGMTString());c.cookie.domain&&(j+="; domain="+c.cookie.domain);j+="; path="+(c.cookie.path||b.urlParts[4]||
"/");d.cookie=j}if(i)c.defaultStorage.setItem(a,f);else if(j=e()){j.setAttribute(a,f);try{j.save("__ud")}catch(h){}}},get:function(a){if(c.cookie){if(g.cookieEnabled){var f=d.cookie,j=f.indexOf(a+"=");return-1!=j?(j+=a.length+1,a=f.indexOf(";",j),-1==a&&(a=f.length),b.decode(f.substring(j,a)||"")):null}return""}if(i)f=c.defaultStorage.getItem(a);else if(j=e()){try{j.load("__ud")}catch(k){}f=j.getAttribute(a)}return f||""}},i=!!c.defaultStorage;b.module("client/storage",c)})(window,light);light.extend({get:function(b){return!b?null:"string"===typeof b?!light.node||/^[\w-]+$/.test(b)?document.getElementById(b):light.node(b)[0]:b.getConfig?b[0]||null:b},write:function(b){if("complete"===document.readyState){var e=document.createElement("span");e.innerHTML=b;document.body.appendChild(e)}else document.write(b)},isHTMLElement:function(b){return b&&(1===b.nodeType||9===b.nodeType)},hasClass:function(b,e){return b?RegExp("(\\s|^)"+e+"(\\s|$)").test(b.className):!1},setStyle:function(b,e){if("string"===
light.type(e)&&2==arguments.length){var d={};d[arguments[0]]=arguments[1];e=d}for(var a in e)d=e[a],"number"===typeof d&&(d+="px"),"opacity"==a?1>d&&0<d&&(isIE&&9>light.client.info.browser.version[0]?b.style.filter="alpha(opacity="+100*d+")":b.style.opacity=1.0E-5>d?0:d):b.style["float"==a||"cssFloat"==a?void 0===typeof b.style.styleFloat?"cssFloat":"styleFloat":a]=d;return this},getStyle:function(b,e){var d=b.currentStyle?b.currentStyle[e]:document.defaultView.getComputedStyle(b,null)[e];"px"===
d.slice(-2)&&(d=parseInt(d,10));return d}});
(function(b){var e=function(a,b){if(!a._fixed){a._fixed=!0;a.target||(a.target=a.srcElement||document);a.data=b||{};3===a.target.nodeType&&(a.target=a.target.parentNode);!a.relatedTarget&&a.fromElement&&(a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement);if(void 0===a.pageX&&void 0!==a.clientX){var f=a.target.ownerDocument||document,g=f.documentElement,f=f.body;a.pageX=a.clientX+(g&&g.scrollLeft||f&&f.scrollLeft||0)-(g&&g.clientLeft||f&&f.clientLeft||0);a.pageY=a.clientY+(g&&g.scrollTop||
f&&f.scrollTop||0)-(g&&g.clientTop||f&&f.clientTop||0)}if(!a.which&&(a.charCode||a.keyCode))a.which=a.charCode||a.keyCode;!a.metaKey&&a.ctrlKey&&(a.metaKey=a.ctrlKey);!a.which&&void 0!==a.button&&(a.which=a.button&1?1:a.button&2?3:a.button&4?2:0);a.cancel=function(){a.preventDefault?a.preventDefault():a.returnValue=false;a.cancelled=true};a.stop=function(){a.stopPropagation?a.stopPropagation():a.cancelBubble=true;a.stopped=true}}},d=/\s+/;b.extend({on:function(a,c,f,g){var h="string"===typeof a?b.get(a):
a;if(h&&c&&"string"===typeof c)if(d.test(c))b.each(c.split(d),function(c,d){b.on(a,d,f,g)});else{var j=function(a){a.cancelled=a.stopped=!1;e(a,g);return!1!==f.call(h,a)&&!a.cancelled};h.addEventListener?h.addEventListener(c,j,!1):h.attachEvent&&h.attachEvent("on"+c,j)}},listen:function(a,c,f){var g=document,h=a,a=a.split(d,2);2===a.length&&(g=b.get(a[0].substr(1)),h=a[1]);b.on(g,c,function(a){for(var c=a.target;c;){if(h.charAt(0)==="."){if(b.hasClass(c,h.substr(1)))break}else if(c.tagName===h.toUpperCase())break;
else if(c===g){c=null;break}c=c.parentNode}c&&f.call(c,a)})},removeEvent:function(a,c,f){(a="string"===typeof a?b.get(a):a)&&(a.removeEventListener?a.removeEventListener(c,f,!1):a.detachEvent("on"+c,f))},cancelEvent:function(a){a.cancel&&a.cancel()}})})(window.light);
(function(b){var e={method:"GET",success:b.noop,failure:b.noop,finish:b.noop,timeoutHandler:b.noop,format:"json",force:!0,async:!0,timeout:-1,contentType:"application/x-www-form-urlencoded"},d={text:{parser:b.trim},json:{parser:b.toJSON,handler:function(a){return a&&"ok"===a.stat},redirector:function(a){a&&a.redirectUrl&&(window[a.target||"self"].location.href=a.redirectUrl)}}},a=0,c=function(c,g,h){if("JSONP"==h.method||"jsonp"==h.format){g=g||{};a++;b.request._callbacks["callback"+a]=h.success||
b.noop;g[h.hook||"_callback"]="light.request._callbacks.callback"+a;h=document.createElement("script");h.setAttribute("type","text/javascript");h.setAttribute("charset","utf-8");var j=c.indexOf("?");-1<j&&(b.extend(g,b.unparam(c.slice(j+1))),c=c.slice(0,j));h.setAttribute("src",c+"?"+b.param(g));document.getElementsByTagName("head")[0].appendChild(h);return null}var g="string"===typeof g?g:b.param(g),i=b.extend({},e,h);i.method=i.method.toUpperCase();var h="GET"===i.method,k=null;i.fail&&(i.failure=
i.fail);h&&i.force&&(g+=(g?"&":"")+"t="+(new Date).getTime().toString(36));window.XMLHttpRequest?k=new XMLHttpRequest:window.ActiveXObject&&(k=new ActiveXObject("Microsoft.XMLHTTP"));h&&g&&(c+=(0<c.indexOf("?")?"&":"?")+g);k.open(i.method,c,i.async);h||k.setRequestHeader("Content-type",i.contentType);k.onreadystatechange=function(){if(k.readyState==4){b.log("Get response with code %d.",k.status);var a={},c=i.failure,g;if(k.status==200){a=d[i.format].parser(k.responseText);(g=d[i.format].redirector)&&
g(a);g=d[i.format].handler;if(!g||g(a)!==false)c=i.success}c.call(k,a);i.finish.call(k)}};b.log("Send ajax request to %s.",c);k.send(h?null:g);return k};c.config=d;b.request=c;b.request._callbacks={}})(window.light);
(function(b){var e=null,d=0,a=function(){var a=b.client.info,c=document.documentMode;return a.hasEngine("trident",6)||a.hasEngine("trident",7)||c&&7>=c?2048-(d+10).toString().length:3500-(d+10).toString().length},c=function(a,c,f){var c=c||"=",d=[];b.each(a,function(f,e){f&&a.hasOwnProperty(f)&&("dataContent"==f?d.push(b.encode(f)+c+e):d.push(b.encode(f)+c+b.encode(e)))});return d.join(f||"&")},f=function(a,f,d,e){b.packetRequest._packetCallbacks["callback"+f]=e||b.noop;a=a+"?"+c(d);f=document.createElement("script");
f.setAttribute("type","text/javascript");f.setAttribute("charset","utf-8");f.setAttribute("src",a);document.getElementsByTagName("head")[0].appendChild(f);b.log("Send ajax request to %s.",a)};b.packetRequest=function(c,h,j,i){function k(a,d){var h=a.info;"fail"==h.packet?(h=n[d],1<h.packet.sendCount&&(h.packet.sendCount--,f(c,h.count,h.packet,function(a){k(a,d)}),b.log("%d: packet request sent again.",d))):"success"==h.packet?(h=n[++d],f(c,h.count,h.packet,function(a){k(a,d)}),b.log("%d: packet request sent.",
d)):"all"==h.packet&&(e&&clearTimeout(e),i.success(a),b.log("all packet request sent successfully."))}var n=[],o={packet:{sendCount:3,dataId:(new Date).getTime(),dataSize:0,dataIndex:0,dataContent:"",_callback:"light.packetRequest._packetCallbacks.callback"}};o.packet=b.extend(o.packet,h);for(var j=b.encode(b.inspect(j)),t=a()-(c+"?"+b.param(o.packet)).length,v=o.packet.dataSize=Math.ceil(j.length/t),l=0;l<v;l++){var h=b.extend(!0,{},o),m=h.packet;m.dataIndex=l;m.dataContent=j.slice(0,t);m._callback=
"light.packetRequest._packetCallbacks.callback"+d;h.count=d++;j=j.slice(t);n.push(h)}f(c,n[0].count,n[0].packet,function(a){k(a,0)});b.log("0: packet request sent.");e=setTimeout(function(){i.abort("\u7f51\u7edc\u5f02\u5e38\uff0c\u8bf7\u91cd\u65b0\u64cd\u4f5c")},1E4)};b.packetRequest._packetCallbacks={}})(window.light);
(function(b,e){var d=!1,a=!!document.addEventListener,c=b.lightReady=b.lightReady||[],f=function(){for(d=!0;c.length;)c.shift().call(b,e,e.node,e.page)};e.on(document,a?"DOMContentLoaded":"readystatechange",a?f:function(){("loaded"==document.readyState||"complete"==document.readyState)&&f()});!a&&b==b.top&&b.setTimeout(function(){try{d||document.documentElement.doScroll("left"),setTimeout(f,0)}catch(a){setTimeout(arguments.callee,20)}},20);e.ready=function(a){d?a.call(b,e,e.node,e.page):c.push(a)}})(window,
light);
(function(b){var e=b.client.info.engine.trident,d=b.client.info.engine.presto,a=function(a){return/^(?:body|html)$/i.test(a.tagName)};b.extend({getViewportHeight:function(c){c=c||window;if(c==window||c==document||a(c)){var c=self.innerHeight,b=document.compatMode;if((b||e)&&!d)c="CSS1Compat"==b?document.documentElement.clientHeight:document.body.clientHeight;return c}return c.offsetHeight},getViewportWidth:function(c){c=c||window;if(c==window||c==document||a(c)){var c=self.innerWidth,b=document.compatMode;if(b||
e)c="CSS1Compat"==b?document.documentElement.clientWidth:document.body.clientWidth;return c}return c.offsetWidth},getScroll:function(c){c=c||document;return c==window||c==document||a(c)?{left:Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),top:Math.max(document.documentElement.scrollTop,document.body.scrollTop)}:{left:c.scrollLeft,top:c.scrollTop}},getOffsets:function(a){if("getBoundingClientRect"in document.documentElement){try{var b=a.getBoundingClientRect()}catch(d){}var e=
a&&a.ownerDocument,a=e.body,e=e.documentElement;return{top:b.top+(window.pageYOffset||e.scrollTop||a.scrollTop)-(e.clientTop||a.clientTop||0),left:b.left+(window.pageXOffset||e.scrollLeft||a.scrollLeft)-(e.clientLeft||a.clientLeft||0)}}b=function(a){var b;b=window.getComputedStyle?getComputedStyle(a,null).position:a.currentStyle?a.currentStyle.position:a.style.position;return"absolute"==b||"fixed"==b?a.offsetParent:a.parentNode};if("undefined"!=typeof a.offsetParent){for(var e=a,j=0,i=0;a;a=a.offsetParent)j+=
a.offsetLeft,i+=a.offsetTop;if(!e.parentNode||!e.style||"undefined"==typeof e.scrollTop)return{left:j,top:i};for(a=b(e);a&&a!=document.body&&a!=document.documentElement;)j-=a.scrollLeft,i-=a.scrollTop,a=b(a);return{left:j,top:i}}return{left:a.x,top:a.y}},region:function(a){var d=b.getOffsets(a);return{left:d.left,top:d.top,width:b.getViewportWidth(a),height:b.getViewportHeight(a)}}})})(window.light);
(function(b){var e={arale:{exists:function(){return!!window.arale},dialog:function(){var a={page:"IframeXbox",string:"StringXbox",dom:"DomXbox"};return function(c){var f=a[c.type];if(!f)throw"Invalid dialog type: "+c.type;var g,e=b.extend({},c);e.isOld=!0;c.trigger&&(e.el=c.trigger);if("string"==c.type)if(d.dialog.template)c.content=b.substitute(d.dialog.template,c);else if("string"!=c.content){var j=document.createElement("div");j.appendChild(c.content);c.content=j.innerHTML}e.value=function(){return c.content};
Loader.use(["aralex.xbox"],function(){g=new aralex.xbox[f](e);c.trigger||g.show()});return this.page.dialog=g}}(),closeDialog:function(a){(a=a||this.page.dialog)&&a.hide()},tooltip:function(a){var c,d=a.trigger,g={targets:d};b.isHTMLElement(d)&&(g.targets=[d]);a.content&&(g.getValue=function(){return a.content});Loader.use(["aralex.apop"],function(){c=new aralex.apop.Tip(g);a.trigger||c.show()})}},alipay:{exists:function(){return!!window.AP},dialog:function(){var a={autoShow:!0,type:"dom",modal:!0};
return function(c){var f,g=b.extend({},a,c);c.trigger&&(g.el=c.trigger);"page"==g.type?g.type="iframe":"dom"!=g.type&&"string"==g.type&&(d.dialog.template?c.content=b.substitute(d.dialog.template,c):"string"!=c.content&&(f=document.createElement("div"),f.appendChild(c.content),c.content=f.innerHTML),g.title="");g.value=function(){return c.content};f=this.page.dialog=new AP.widget.xBox(g);g.autoShow&&f.show();return f}}(),closeDialog:function(){b.page.dialog=null;AP.widget.xBox.hide()},tooltip:function(a){var c=
a.trigger,d={width:"auto"};b.isHTMLElement(c)&&(c=[el]);a.content&&(d.message=a.content);return new AP.widget.popNotice(c,d)}},"default":{exists:function(){return!0},dialog:function(a){alert(a.title)},closeDialog:function(){},tooltip:function(a){alert(a.content)}}},d=b.module("page/ui",{detect:function(){var a;b.each(e,function(b,d){if(d.exists())return a=d,!1});return a}});b.each(["dialog","tooltip"],function(a,c){d[c]=function(a){var g=d.detect();g&&g[c].call(b,a)}});d.closeDialog=function(){var a=
d.detect();a&&a.closeDialog.call(b)}})(window.light);
(function(b,e){var d=function(a,c){if(!this.getConfig)return new d(a,c);if(!arguments.length||!a)return this;if(a.getConfig)return a;if(b.isHTMLElement(a))return a._light_node||this.add(a);if("string"!==typeof a&&a.length)return this.add(a);if("string"===typeof a){var e=d.getSizzle(),g=c;"string"===typeof g?g=b.get(g):g&&g.getConfig&&(g=g[0]);g=g||document;if(e)e=e(a,g);else if(document.querySelectorAll)e=g.querySelectorAll(a);else throw"method not supported";e.length&&this.add(e)}return this};d.getSizzle=
function(){var a;return function(){if(a)return a;b.Sizzle?a=b.Sizzle:window.YAHOO?a=YAHOO.util.Dom.query:window.arale&&arale.dom&&arale.dom.sizzle&&(a=arale.dom.sizzle);return a||window.Sizzle}}();d.prototype={length:0,each:function(a){for(var b=0;b<this.length&&!1!==a.call(this[b],b,this[b]);)b++;return this},map:function(a){return b.map(this,a)},toArray:function(){return b.toArray(this)},add:function(a){var c;if("string"===typeof a)c=b.get(a);else if("object"===typeof a)if(!a.nodeType&&a.length&&
a[0])for(var e=0,g=a.length;e<g;e++){var h=a[e];if(b.isHTMLElement(h)){this[this.length]=h;this.length++;var j=new d;j[0]=h;j.length=1;h._light_node=j}}else c=a;b.isHTMLElement(c)&&(this[this.length]=c,this.length++);return this},clear:function(){for(var a=0;a<this.length;delete this[a++]);this.length=0;return this},clone:function(){for(var a=new d,b=a.length=this.length;b--;)a[b]=this[b];return a},on:function(a,c){return this.each(function(){b.on(this,a,c)})},show:function(){return this.each(function(){this.style.display=
""})},hide:function(){return this.each(function(){this.style.display="none"})},toggle:function(a){var c,d=!1;a!==e&&(b.isFunction(a)?d=!0:c=a?"":"none");return this.each(function(){var b=c;b===e&&(b=d?a.apply(this)?"":"none":"none"===this.style.display?"":"none");this.style.display=b})},item:function(a){var b=new d;this[a]&&b.add(this[a]);return b},slice:function(){return new d(Array.prototype.slice.apply(this,arguments))}};b.each(["mouseover","mouseout","change"],function(a,b){d.prototype[b]=function(a){return this.on(b,
a)}});b.each(["click","submit","focus","blur"],function(a,b){d.prototype[b]=function(a){return a===e?this.each(function(){this[b]()}):this.on(b,a)}});b.node=d})(window.light);
(function(b,e){e.build=function(){var a={td:["<table><tbody><tr>","</tr></tbody></table>"],tr:["<table><tbody>","</tbody></table>"],option:["<select>","</select>"],optgroup:["<select>","</select>"]},c=/<(.+?)\b/;return function(d,f){var k=b.createElement("div"),n;if(c.test(d)){var o=d,t=o.match(c)[1].toLowerCase(),v=a[t];v&&(o=v[0]+o+v[1]);k.innerHTML=o;return e(t+":first",k)}k=light.trim(d);n=b.createElement(k);light.each(f,function(a,b){"className"===a?n[a]=b:("boolean"===typeof b&&(b=b?a:""),n.setAttribute(a,
b))});return new e(n)}}();var d=function(a,b){var c=e.getSizzle();if(!c||!c.filter)throw"method not supported";return c.filter(a,[b]).length},a=function(a,b,c){var f=this[0],k=new e;if(!f)return k;for(;f=f[b];)if(1===f.nodeType&&(!a||d(a,f)))if(k.add(f),c)break;return k},c=function(a,b,c){var d=b;if(d instanceof e)d=d[0];else if(!light.isHTMLElement(d))return!1;return this.each(function(){c?d[a](this):this[a](d)})},f=function(a,b){var c=[];if("string"===typeof a){var d=e.getSizzle();if(!d||!d.filter)throw"method not supported";
c=d.filter(a,this,!1,b)}else this.each(function(b){a.call(this,b,this)&&c.push(this)});return this.clear().add(c)};light.extend(e.prototype,{find:function(a){return new e(a,this)},filter:function(a){return f.call(this,a,!1)},remove:function(a){return f.call(this,a,!0)},del:function(){return this.each(function(){this.parentNode.removeChild(this)}).clear()},append:function(a){return c.call(this,"appendChild",a)},appendTo:function(a){return c.call(this,"appendChild",a,!0)},text:function(a){var c="innerText"in
b.createElement("div")?"innerText":"textContent";if(void 0===a){var d=this[0];return!d?"":light.trim(d[c])}return this.each(function(){this[c]=a})},html:function(a){if(void 0===a){var b=this[0];return!b?"":light.trim(b.innerHTML)}return this.each(function(){this.innerHTML=a})},next:function(b){return a.call(this,b,"nextSibling",!0)},nextAll:function(b){return a.call(this,b,"nextSibling",!1)},prev:function(b){return a.call(this,b,"previousSibling",!0)},prevAll:function(b){return a.call(this,b,"previousSibling",
!1)},siblings:function(b){return a.call(this,b,"previousSibling",!1).add(a.call(this,b,"nextSibling",!1))},parent:function(b){return a.call(this,b,"parentNode",!0)},children:function(a){var b=this[0],c=new e;if(!b||!b.firstChild)return c;b=b.firstChild;do 1===b.nodeType&&(!a||d(a,b))&&c.add(b);while(b=b.nextSibling);return c},style:function(a){if(void 0===a)return this;if("string"===typeof a){var b=this[0];return!b?"":light.getStyle(b,a)}return this.each(function(){light.setStyle(this,a)})}})})(window.document,
light.node);
light.extend(light.node.prototype,{attr:function(b,e){if(void 0===e){var d=this[0];return!d?"":"undefined"!==typeof d.getAttribute&&"boolean"!==typeof d[b]?d.getAttribute(b):d[b]}return this.each(function(){"undefined"!==typeof this.setAttribute?!1===e?(this.setAttribute(b,""),this.removeAttribute(b),b in this&&(this[b]=!1)):(this.setAttribute(b,!0===e?b:e),b in this&&(this[b]=e)):b in this&&(this[b]=e)})},getConfig:function(b,e){var d=this.attr(b||"data-config"),a={};d&&(a=light.unparam(d),e&&light.each(a,
e));return a},hasClass:function(b){var e=this[0];return!e||!e.className?!1:RegExp("(?:^|\\s)"+b+"(?:\\s|$)").test(e.className)},addClass:function(b){if(!b)return this;var e=RegExp("(?:^|\\s)"+b+"(?:\\s|$)");return this.each(function(){var d=this.className;d?e.test(d)||(this.className+=" "+b):this.className=b})},removeClass:function(b){if(!b)return this;var e=RegExp("(?:^|\\s)"+b+"(\\s|$)");return this.each(function(){var b=this.className;b&&e.test(b)&&(this.className=b.replace(e,"$1"))})},toggleClass:function(b,
e){var d=e?this.addClass:this.removeClass;if(void 0===e){var a=this;return this.each(function(){d=light.node(this).hasClass(b)?a.removeClass:a.addClass;d.call(a,b)})}return d.call(this,b)}});
light.extend(light.node.prototype,{val:function(b){if(void 0===b){var e=this[0];if(!e)return"";(e=e.value||"")&&(e=light.unescapeHTML(light.trim(e)));return e}return this.each(function(){this.value=b})},field:function(b,e){if(void 0===e){if(!b)return"";var d=this[0];if(!d)return"";var a=d[b];!a&&d.item&&(a=d.item(b));return!a||!a.value?"":light.unescapeHTML(light.trim(a.value))}return this.each(function(){var a=this[b];!a&&this.item&&(a=this.item(b));a&&(a.value=e)})},serialize:function(){var b=this[0];
if(!b)return"";var e=[];light.node(":input[name]",b).each(function(b,a){var c=a.value;a.disabled||("radio"==a.type||"checkbox"==a.type)&&!a.checked||e.push(light.encode(a.name)+"="+light.encode(c))});return e.join("&")}});
(function(b){b.prototype.captcha=function(b){var d="string"===typeof b?light.get(b):b;if(!d)return this;d.length&&(d=d[0]);var a=this[0];if(!a)return this;light.on(b,"click",function(b){b.cancel();var b=a.src.split("?"),d=light.unparam(b[1]||"");d.t=(new Date).getTime();a.src=b[0]+"?"+light.param(d)});return this}})(light.node);
(function(b,e,d){var a={types:{email:[/^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/,"\u90ae\u4ef6\u5730\u5740"],phone:[/^(\d{3,4}-)\d{7,8}(-\d{1,6})?$/,"\u7535\u8bdd\u53f7\u7801"],mobile:[/^1\d{10}$/,"\u624b\u673a\u53f7\u7801"],date:[/^\d{4}\-[01]?\d\-[0-3]?\d$|^[01]\d\/[0-3]\d\/\d{4}$/,"\u65e5\u671f"],integer:[/^[1-9][0-9]*$/,"\u6570\u5b57"],number:[/^[+-]?[1-9][0-9]*(\.[0-9]+)?([eE][+-][1-9][0-9]*)?$|^[+-]?0?\.[0-9]+([eE][+-][1-9][0-9]*)?$/,"\u6570\u503c"],money:[/^\d+(\.\d{0,2})?$/,
"\u91d1\u989d"],cnID:[/^\d{15}$|^\d{17}[0-9a-zA-Z]$/,"\u8eab\u4efd\u8bc1\u53f7"],chinese:[/^[\u2E80-\uFE4F]+$/,"\u6c49\u5b57"],zip:[/^[0-9]{6}$/,"\u90ae\u653f\u7f16\u7801"],bankname:/^[a-zA-Z0-9\u4e00-\u9fa5]+$/,name:/^([\u4e00-\u9fa5|A-Z|\s]|\u3007)+([\.\uff0e\u00b7\u30fb]?|\u3007?)+([\u4e00-\u9fa5|A-Z|\s]|\u3007)+$/,realName:/^([\u4e00-\u9fa5|a-zA-Z|\s]|\u3007)+([\.\uff0e\u00b7\u30fb]?|\u3007?)+([\u4e00-\u9fa5|a-zA-Z|\s]|\u3007)+$/},options:{required:d,checkOnBlur:!1,stopOnError:!1,containerSelector:".fm-item",
labelHandler:d,errorClass:"fm-error",tipSelector:d,tipTemplate:'<div class="fm-explain">{text}</div>',message:"{label}\u586b\u5199\u4e0d\u6b63\u786e"},messages:{1:"",2:"\u8bf7\u586b\u5199{label}",3:"\u586b\u5199\u7684{label}\u4e0d\u80fd\u88ab\u8bc6\u522b\u4e3a{type}",4:"{label}\u7684\u957f\u5ea6\u4e0d\u80fd\u5927\u4e8e {value}",5:"{label}\u7684\u957f\u5ea6\u4e0d\u80fd\u5c0f\u4e8e {value}",6:"\u4e24\u6b21\u8f93\u5165{label}\u4e0d\u5339\u914d"},ruleOptions:{autoTrim:!0,visibleOnly:!1,required:d,checkOnBlur:d,
maxLength:d,minLenth:d,sameWith:d,type:d,message:d}},c=function(c,d){this.form=b.get(c.form);if(!this.form)throw"form not found";this.rules=d||{};this.options=b.extend({},a.options,c);this.init();var e=this;"FORM"===this.form.tagName&&b.on(this.form,"submit",function(a){e.validate()||a.cancel()})};a.rules={minLenth:function(a,b,c){if(b.length<c)return 4},maxLenth:function(a,b,c){if(b.length>c)return 5},sameWith:function(a,c,d){a=this.form.field(d);a=a.length?a[0]:b.get(d);return!a?!1:c===a.value?
0:6},expression:function(a,c,d){if(!d)return 0;a=d;a=-1===a.indexOf("#")?c+" "+a:a.replace(/#/g,c);b.log("evaluating %s",a);try{return eval(a)?0:1}catch(e){return 1}},type:function(c,d,e){var j=!1;b.each(e.split("|"),function(c,e){if(!e)return 0;var f=a.types[e];if(!f)return 0;b.isArray(f)&&(f=f[0]);j=f.test(d);return!j});return j?0:1}};c.prototype=function(){var c={focus:"onfocusin",blur:"onfocusout"},g=function(a,b){var d=this,e=c[a],g=function(a){a=a.target||a.srcElement;a.name&&b.call(d,a)};e in
this.form?this.form.attachEvent(e,g):this.form.addEventListener(a,g,!0)},h=function(a){var b="";switch(a.tagName){case "SELECT":b=a.multiple?e("option:selected",a).map(function(a){return a.value}).join():a.value;break;case "INPUT":if(b=a.type.toLowerCase(),"radio"===b||"checkbox"===b){b=e(a).parent("form").find('[name="'+a.name+'"]:checked').map(function(a){return a.value}).join();break}default:b=a.value}return b},j=function(a,b,c){"false"===b&&(c[a]=!1)},i=function(c,f){var g=this.options;if(!c.name||
!g.required&&!c.getAttribute("data-validate"))return 0;this.rules[c.name]=b.extend({},a.ruleOptions,c._rule=c._rule||e(c).getConfig("data-validate",j),this.rules[c.name]);var i=this.rules[c.name],l=this.rules[c.name].checkOnBlur;if(!1===l||l===d&&!f&&!this.options.checkOnBlur||i.visibleOnly&&!c.offsetHeight)return 0;var m=h(c),q=0,u="default";i.before&&(i.autoTrim&&(m=b.trim(m)),q=i.before.call(this,c,m));if(!q)if(m=h(c),i.autoTrim&&(m=b.trim(m)),l=i.required,l===d&&(l=g.required),b.isFunction(l)&&
(l=l.call(this,c)),m){var y=g.stopOnError;b.each(i,function(b,e){if(e===d||!a.rules[b])return true;(q=a.rules[b].call(this,c,m,e))&&b==="type"&&(u=e);return!y||!q})}else l&&(q=2);if(q){var l=a.messages[q]||i.message,r={value:m};l||(u&&a.types[u]&&a.types[u][1]?(r.type=a.types[u][1],l=a.messages[3]):l=g.message);var w=e(c).addClass("validating").parent(g.containerSelector);i.tipSelector&&(w=e(g.tipSelector,w));w.addClass(g.errorClass);var x=i.label;!x&&g.labelHandler&&(x=g.labelHandler.call(this,c));
r.label=x.replace(/[\uff1a:]/g,"")||"\u6b64\u9879";l=b.substitute(l,r);b.log("error found in %s: %s (%d)",c.name,l,q);r=c.parentNode;r._tip&&r._tip.del();r._tip=e.build(b.substitute(g.tipTemplate,{text:l})).appendTo(i.tipSelector?w:r)}else k.call(this,c);return q},k=function(a){if(this.options.required||a.getAttribute("data-validate")){var b=this.options;e(a).parent(b.containerSelector).removeClass(b.errorClass);(a=a.parentNode._tip)&&a.del()}};return{init:function(){g.call(this,"blur",i);g.call(this,
"focus",k)},addRule:function(a,c){var d=this.rules;d[a]||(d[a]={});b.extend(d[a],c)},validate:function(){var a=this,b=this.options,c=0,d=this.options.stopOnError;b.before&&(c+=b.before.call(this)||0);d&&c||e(":input",this.form).each(function(){c+=i.call(a,this,!0)||0;return!d||!c});b.after&&(c+=b.after.call(this,!c)||0);return!c}}}();b.validator=b.extend(c,a)})(light,light.node);
(function(b){function e(b,a,c){b=c.createElement(b);if(null===a)return b;for(p in a)if("class"==p||"className"==p)b.className=a[p];else if("style"==p)for(s in a[p])b.style[s]=a[p][s];else"innerHTML"===p?b.innerHTML=a[p]:"appendTo"===p?a[p].appendChild(b):"append"===p?b.appendChild(a[p]):b.setAttribute([p],a[p]);return b}b.dialog=function(d){if(b.page._dialog)return b.page._dialog;this.config=b.extend({},{targetFrame:document,title:"\u5b89\u5168\u63a7\u4ef6\u63d0\u793a",bodyId:"light-dialog",bodyClass:"light-dialog",
iframeId:"light-dialog-iframe",overlayId:"light-dialog-shadow",overlayClass:"light-dialog-shadow",loadingId:"light-load",loadClass:"light-load",loadingSrc:"https://img.alipay.com/global/loading.gif",iframeSrc:"https://securitycenter.alipay.com/sc/aliedit/xbox.htm",timeout:2E4},d);var a=this.config.targetFrame;this.body=a.getElementById(this.config.bodyId);this.overlay=a.getElementById(this.config.overlayId);this.load=a.getElementById(this.config.loadingId);var c=function(){var c="",d="",e=a.compatMode,
f=b.client.info;if(e||f.engine.trident)"CSS1Compat"==e?(c=a.documentElement.clientWidth,d=a.documentElement.clientHeight):(c=a.body.clientWidth,d=a.body.clientHeight);document.all?(e=document.body.scrollTop,f=document.body.scrollLeft):(e=window.pageYOffset,f=window.pageXOffset);return{maxWidth:Math.max(a.documentElement.clientWidth,a.body.scrollWidth,a.documentElement.scrollWidth,a.body.offsetWidth,a.documentElement.offsetWidth),maxHeight:Math.max(a.documentElement.clientHeight,a.body.scrollHeight,
a.documentElement.scrollHeight,a.body.offsetHeight,a.documentElement.offsetHeight),clientWidth:c,clientHeight:d,scrollTop:e,scrollLeft:f}},f=this;b.page._dialog=f;b.ready(function(){if(!f.body){f.body=e("div",{id:f.config.bodyId,"class":f.config.bodyClass,style:{left:Math.max((c().clientWidth-620)/2+c().scrollLeft,0)+"px",top:Math.max((c().clientHeight-400)/2+c().scrollTop,0)+"px"},appendTo:a.body},a);var d=function(){f.body.style.left=Math.max((c().clientWidth-620)/2+c().scrollLeft,0)+"px";f.body.style.top=
Math.max((c().clientHeight-400)/2+c().scrollTop,0)+"px"};b.on(window,"resize",d);b.on(window,"scroll",d);f.body.innerHTML='<div class="light-dialog-top"><div class="light-dialog-title"><h2>'+f.config.title+'</h2><a href="#" id="light-dialog-close"><s></s><em>\u5173\u95ed</em></a></div></div>';f.iframe=e("iframe",{id:f.config.iframeId,frameBorder:"no",scrolling:"no",src:"",appendTo:f.body},a)}f.overlay||(f.overlay=e("div",{id:f.config.overlayId,"class":f.config.overlayClass,innerHTML:"<iframe src=\"javascript:''\"></iframe>",
style:{width:c().maxWidth+"px",height:c().maxHeight+"px"},appendTo:a.body},a),b.on(window,"resize",function(){f.overlay.style.width=c().maxWidth+"px";f.overlay.style.height=c().maxHeight+"px"}));f.load||(f.load=e("div",{id:f.config.loadingId,"class":f.config.loadClass,innerHTML:'<img src="'+f.config.loadingSrc+'">',style:{left:(c().clientWidth-208)/2+"px",top:(c().clientHeight-50)/2+"px"},appendTo:a.body},a))})};b.dialog.prototype={show:function(){var d=this;this.load.style.visibility="visible";this.overlay.style.visibility=
"visible";b.on(this.iframe,"load",function(){d.body.style.visibility="visible";d.load.style.visibility="hidden";var a=d.config.targetFrame.getElementById("light-dialog-close")||{};b.on(a,"click",function(){d.hide()});b.on(d.config.targetFrame,"keydown",function(a){27==a.which&&(d.hide(),a.cancel())})});this.iframe.src=this.config.iframeSrc},hide:function(){this.body.style.visibility="hidden";this.overlay.style.visibility="hidden"},dispose:function(){targetFrame.body.removeChild(this.load);targetFrame.body.removeChild(this.body);
targetFrame.body.removeChild(this.overlay)},onShow:b.noop};b.dialog.prototype.constructor=b.dialog})(window.light);
(function(b){b.pop=function(e){this.options=b.extend({},{targets:[],id:"",className:"",width:280,height:null,type:"message",event:"mouseover",direction:"up"},e);this.pop=null;this.init()};b.pop.position={up:function(b,d,a,c,f){f.direction=b;d.height+d.top-a.top-a.height<c.height+f.height?f.direction="down":a.top-d.top<c.height+f.height&&(f.direction="up");"up"==f.direction?(c.top=a.top+a.height+f.height,f.top=1-f.height):(c.top=a.top-f.height-c.height,f.top=c.innerHeight-1);c.left=a.left<d.left+parseInt(c.width/
2)-a.width?d.left:a.left>d.left+d.width-parseInt(c.width/2)?d.left+d.width-c.width:a.left+parseInt(a.width/2)-parseInt(c.width/2);f.left=a.left<c.left?0:a.left>c.left+c.width?c.width-f.width:a.width<c.width?a.left+parseInt((a.width-f.width)/2)-c.left:parseInt(c.width/2);return{rect:c,arrow:f}},left:function(){}};b.pop.position.down=b.pop.position.up;b.pop.position.left=b.pop.position.right;b.pop.prototype={init:function(){var e=this;this.initDom();b.each(this.options.targets,function(d,a){a=b.node(a);
a.mouseover(function(){e.show(a)}).mouseout(function(){e.hide(a)})})},initDom:function(){this.wrap=b.node.build(b.substitute('<div id="{id}" class="{className}"><div class="ui-tiptext-container ui-tiptext-container-{type}"><span class="ui-tiptext-arrow ui-tiptext-arrowup"></span><span class="ui-tiptext-icon"></span><div class="ui-tiptext-content"></div></div></div>',{id:this.options.id,className:this.options.className,type:this.options.type})).appendTo(document.body).hide();this.pop=b.node(".ui-tiptext-container",
this.wrap);this.arrow=b.node(".ui-tiptext-arrow",this.pop);this.content=b.node(".ui-tiptext-content",this.pop)},show:function(b){this.content.html(b.attr("data-content"));this.setSize();this.wrap.show();this.setPosition(b[0])},hide:function(){this.wrap.hide()},setSize:function(){this.options.width&&(this.pop[0].style.width=this.options.width+"px");this.options.height&&(this.pop[0].style.height=this.options.height+"px")},setPosition:function(e){var d;d=b.getScroll();var e=b.region(e),a=b.region(this.pop[0]),
c=b.region(this.arrow[0]);a.innerHeight=this.pop[0].clientHeight;d.width=b.getViewportWidth();d.height=b.getViewportHeight();d=b.pop.position[this.options.direction](this.options.direction,d,e,a,c);b.setStyle(this.pop[0],{position:"absolute",zIndex:"9999",left:d.rect.left+"px",top:d.rect.top+"px"});b.setStyle(this.arrow[0],{left:d.arrow.left+"px",top:d.arrow.top+"px"});this.arrow[0].className="ui-tiptext-arrow ui-tiptext-arrow"+d.arrow.direction}}})(window.light);light.has("/alipay/security/base")||function(f){var h=f.client.info,i=0,j=[],e=function(a){if(a!==j)throw"invalid constructor, use create() instead.";},k=function(a,d){return a&&d&&1===a.nodeType&&"undefined"!==typeof a[d]};f.register("alipay/security/base",window,e);var g=alipay.security;e.defaults={id:"",container:null,msgMode:"quiet",msgTitle:"",msgNormalAttribute:"data-explain",msgFormItemContainer:null,msgClass:"fm-explain",msgErrorClass:"fm-error",msgHandler:null};e.Name="base";e.properties=
{element:null,_readyList:[]};g.monitor=function(a,d){window.monitor&&monitor.log("sc",a||"unknown",d);f.track("sc-"+a+"-"+d)};g.create=e.create=function(a,d){if(!a)throw"invalid param";var b=new a(j);b.__type=a;var c=e.defaults;a.defaults&&(a.defaults=c=f.extend({},e.defaults,a.defaults));c=b.options=f.extend({},c,d);c.id||(i++,c.id="_secprd_"+i);!f.get(c.id)&&"string"===typeof c.container&&(c.container=f.get(c.container));f.extend(b,e.properties,a.properties);a.prototype.postInit&&a.prototype.postInit.call(b);
return b};g.activeXEnabled=e.activeXEnabled=function(){if(!window.ActiveXObject)return!1;var a=window.external;try{if(a&&"undefined"!=typeof a.msActiveXFilteringEnabled&&a.msActiveXFilteringEnabled())return!1}catch(d){}return!0}();g.refreshStatus=e.refreshStatus=function(a){var d=a.installed=!1,b=h.engine.trident?a.info.activex:a.info.plugin;if(!b)return!1;if(h.engine.trident){if(!g.activeXEnabled)return!1;var c;try{c=new ActiveXObject(b),d=!!c}catch(f){}finally{}}else h.engine.presto&&(b=b.replace(/,/,
"")),d=!(!navigator.plugins||!navigator.plugins[b]);return a.installed=d};e.prototype={toString:function(){return this.__type.Name+" ("+this.options.id+")"},ready:!1,onready:function(a){this.ready?a.apply(this):this._readyList.push(a)},hasAPI:function(a){return k(this.element,a)},dispose:function(){this.element&&(this.element.parentNode.removeChild(this.element),this.element=null);this.ready=!1;this._readyList.length=0},api:function(a,d){if(!this.hasAPI(a))throw"Property is not available: "+a;try{return void 0===
d?this.element[a]:this.element[a]=d}catch(b){this.catchError.call(this,a,b)}return null},render:function(){var a=!1,d=function(){var b=this,c=f.get(this.options.id);if(k(c,this.__type.defaultMethod)){this.element=c;this.ready=!0;this.__type.renderHandler&&(a=!1===this.__type.renderHandler.call(this,!1));for(c=this._readyList;c.length;)c.shift().apply(this)}else a||setTimeout(function(){d.call(b)},0)},b=function(a,c,b){this.__type.renderingHandler&&this.__type.renderingHandler.call(this,!0);f.isFunction(c)&&
this._readyList.push(c);b||(c=this.options.container||document.body,c.childNodes.length?(b=document.createElement("span"),b.innerHTML=a,c.appendChild(b)):c.innerHTML=a);d.call(this)},c=function(){var a=this,b=this.__type;g.refreshStatus(b);b.installed?(f.log("Plugin just installed."),b.installedHandler&&b.installedHandler.call(this)):setTimeout(function(){c.call(a)},10)};return function(a,d){if(!this.alive){this.alive=!0;var e=f.extend({},this.__type.info,this.options),g=this;this.__type.installed||
c.call(this);f.ready(function(){b.call(g,f.substitute(g.__type.template,e),a,d)})}}}(),getMessage:function(a){var d,b=this.__type;f.each(b.message,function(b,f){if(-1!==b.indexOf("-")){var e=b.split("-",2),g=parseInt(e[0],10)||Number.MIN_VALUE,e=parseInt(e[1],10)||Number.MAX_VALUE;found=a>=g&&a<=e}else found=b==a;found&&(d=f);return!found});d||(d=b.message[0]);return d},showMessage:function(a){var d=0,b="",c=this.options.msgMode;"string"===typeof a?b=a:"object"===typeof a&&(void 0!==a.status?(d=a.status,
b=a.msg):void 0!==a.number&&(d=a.number,b=a.description));b||(b="\u672a\u77e5\u9519\u8bef",f.log("Cannot determine message %s.",a));a={title:"\u8fd0\u884c\u8fc7\u7a0b\u4e2d\u53d1\u751f\u9519\u8bef",type:"string",content:b,code:d,show:!0};switch(c){case "dialog":case "tooltip":f.page.ui[c](a);break;case "form":break;case "custom":f.log("Handler not found.");break;default:f.log("%d, %s",a.code,a.content)}},catchError:function(a,d,b){var c=this.__type,e=d.status||d.number||0;0>e&&(e=(4294967295+e+1).toString(16));
f.log("Caught error %s from %s in action %s.",e,c.Name,a);g.monitor(c.Name,e);b||this.showMessage(d)}}}(window.light);light.has("/security/edit")||function(a,g){var c=light.client.info,f=function(){var g="windows"==c.os.name?"Alipay security control":"macos"==c.os.name?"Aliedit Plug-In":"linux"==c.os.name?"Aliedit":"",a="";if("windows"==c.os.name)a="//download."+light.baseDomain+"/sec/edit/aliedit.exe";else if("macos"==c.os.name)"safari"==c.browser.name&&5<=navigator.userAgent.toLowerCase().match(/version\/(\d+\.\d+)/)[1]&&(a="//download."+light.baseDomain+"/aliedit/wkaliedit/1002/wkaliedit.dmg");else if("linux"==
c.os.name&&("firefox"==c.browser.name||"chrome"==c.browser.name||"opera"==c.browser.name))a="//download."+light.baseDomain+"/alipaysc/linux/aliedit/1.0.3.20/aliedit.tar.gz";g={activex:"Aliedit.EditCtrl",plugin:g,classId:"488A4255-3236-44B3-8F27-FA1AECAA8844",type:"application/aliedit",version:"2.4.0.1",editSrc:a,cssSrc:(light.debug?"http://assets.dev.alipay.net":"https://assets.alipay.com")+("/al/alice.components.secuirty-edit-1.1"+(light.debug?"-SNAPSHOT-src":"")+".css"),installationPage:"//securitycenter."+
light.baseDomain+"/sc/npedit/dialog.htm"};return{Name:"control.edit",info:g,template:c.engine.trident?'<object id="{id}" classid="clsid:{classId}" width="{width}" height="{height}" tabindex="{tabindex}"><param name="wmode" value="opaque" /><param name="cm5ts" value="{timestamp}" /><param name="cm5pk" value="{pk}" /><param name="PasswordMode" value="{passwordMode}" /><param name="CryptoMode" value="4" /></object>':'<object id="{id}" name="{name}" type="{type}" width="{width}" height="{height}" tabindex="{tabindex}"><param name="PasswordMode" value="{passwordMode}" /></object>',
available:!!g.editSrc,defaultMethod:"TextData"}}(),j=function(){g.cookie={days:365,domain:"."+light.baseDomain,path:"/"};var a=g.get("ac-stat"),k=null,h=!1,l=!1,e=function(){var b=this;"no"==a&&(g.set("ac-stat","success"),light.track("ac-success"));if(!c.engine.trident){var i=1;window.setTimeout(function(){var a=b.element.getElementsByTagName("param");a||window.setTimeout(arguments.callee,100);a[0].name=="PasswordMode"&&a[0].value=="0"&&function(){try{b.element.PasswordMode=0}catch(a){light.track(c.browser.name+
"-alieditBox-password-error")}if(b.element.PasswordMode!==0&&i<20){i++;window.setTimeout(arguments.callee,100)}}()},100)}},d=function(){if(window.top!==window){var b=document.domain.split(".");1<b.length&&(document.domain=b[b.length-2]+"."+b[b.length-1])}if(!a||"success"==a)g.set("ac-stat","no"),light.track("ac-no");(b=location.pathname)&&/payment\/cashier\.htm/.test(b)&&light.track("ac-no-cashier");var i=this,d=document,b=window,c={},e=f.info;try{if(window.top.document.body){d=window.top.document;
do if(c=null!=b.frameElement?b.frameElement:{},/xbox/i.test(c.name)||/xbox/i.test(c.id))h=!0;while((b=b.parent)!=window.top&&!h);k=new light.dialog({targetFrame:d,iframeSrc:e.installationPage})}}catch(j){l=!0}f.detect=function(){try{l||h?e.editSrc?(alert("\u60a8\u8fd8\u672a\u5b89\u88c5\u5bc6\u7801\u5b89\u5168\u63a7\u4ef6\uff0c\u5b89\u88c5\u540e\u5373\u53ef\u8f93\u5165\u5bc6\u7801\u3002"),location.href=e.editSrc):alert("\u60a8\u73b0\u5728\u6240\u7528\u7684\u6d4f\u89c8\u5668\uff0c\u6682\u4e0d\u652f\u6301\u5b89\u5168\u63a7\u4ef6\u3002"):
k&&k.show()}catch(b){e.editSrc?(alert("\u60a8\u8fd8\u672a\u5b89\u88c5\u5bc6\u7801\u5b89\u5168\u63a7\u4ef6\uff0c\u5b89\u88c5\u540e\u5373\u53ef\u8f93\u5165\u5bc6\u7801\u3002"),location.href=e.editSrc):alert("\u60a8\u73b0\u5728\u6240\u7528\u7684\u6d4f\u89c8\u5668\uff0c\u6682\u4e0d\u652f\u6301\u5b89\u5168\u63a7\u4ef6\u3002")}return!1};(function(){i.options.container.innerHTML='<a href="'+e.installationPage+'" class="aliedit-install J_aliedit_xbox_link" seed="ac-link-tips">\u8bf7\u70b9\u6b64\u5b89\u88c5\u63a7\u4ef6</a>';
var b=i.options.container.getElementsByTagName("a")[0];light.on(b,"click",function(b){b.cancel();f.detect()});setTimeout(function(){var b=light.node.build("div",{className:"edit-tips",id:"edit-tips"});b.html('<a class="edit-tips-text" href="'+e.installationPage+'" seed="ac-link-intro">\u63a7\u4ef6\u53ef\u4fdd\u62a4\u60a8\u8f93\u5165\u4fe1\u606f\u7684\u5b89\u5168</a><div class="edit-tips-angle"></div>');b.appendTo(i.options.container);light.on(b[0],"click",function(b){b.cancel();f.detect()});var a=
d.head||d.getElementsByTagName("head")[0]||d.documentElement;a.getElementsByTagName("link");var c=d.createElement("link");c.setAttribute("charset","utf-8");c.setAttribute("rel","stylesheet");c.setAttribute("href",e.cssSrc);a.appendChild(c);light.on(document.body,"click",function(a){a=window.event||a;a=a.srcElement||a.target;b[0]&&void 0!=a.id&&(b[0].className="fn-hide")})},1500)})()};return{postInit:function(){if(this.__type.installed){var b=this;this.onready(function(){e.call(b)})}else d.call(this)},
getInfo:function(b){if(!this.__type.installed)return"";var a="",c={ci1:"mac",ci2:"ipproxy",alieditVersion:"version",pw:"password"}[b];if(!this.element)return"";if("pw"!=b)try{a=this.element[b]();if(/XOR_1_0{30}_/.test(a)||/(?:\d\.){3}\d/.test(a))return a;if("ci2"==b&&""===a)return"";light.track("ac-"+c+"-invalid",!0);return""}catch(d){return light.track("ac-"+c+"-interface-error",!0),""}else{a=this.element.TextData;if(/3DES_2_0{30}_/.test(a))return a;light.track("ac-"+c+"-invalid",!0);return""}},
getCi1:function(){return this.getInfo("ci1")},getCi2:function(){return this.getInfo("ci2")},getVersion:function(){return this.getInfo("alieditVersion")},getPassword:function(){return this.getInfo("pw")}}}(),f=a.edit=light.deriveFrom(a.base,j,f);f.defaults={};a.refreshStatus(a.edit)}(alipay.security,light.client.storage);
light.has("/security/npedit")||function(a,g){var c=light.client.info,f=function(){var a={activex:"npAliSecCtrl.SecCtrl",plugin:"Alipay Security Control 3",classId:"8EB7C6CB-2DA6-4ABE-B2EA-EAC5A372E757",type:"application/x-alisecctrl-plugin",version:"2.4.0.1",editSrc:"//download."+light.baseDomain+"/sec/edit/aliedit.exe",cssSrc:(light.debug?"http://assets.dev.alipay.net":"https://assets.alipay.com")+("/al/alice.components.secuirty-edit-1.1"+(light.debug?"-SNAPSHOT-src":"")+".css"),installationPage:"//securitycenter."+
light.baseDomain+"/sc/npedit/dialog.htm"};return{Name:"control.npedit",info:a,template:c.engine.trident?'<object id="{id}" name="{name}" classid="clsid:{classId}" width="{width}" height="{height}" tabindex="{tabindex}"><param name="prop" value="{prop}"></object>':'<object id="{id}" name="{name}" type="{type}" width="{width}" height="{height}" prop="{prop}" tabindex="{tabindex}"><param name="handler" value="{handler}"></object>',available:a.editSrc?!0:!1,minVersion:"1.0.0.1",defaultMethod:"GetMiscInfo"}}(),
j=function(){g.cookie={days:365,domain:"."+light.baseDomain,path:"/"};var a=g.get("ac-stat"),f=function(){"no"==a&&(g.set("ac-stat","success"),light.track("ac-success"));try{var h=this.element.GetMiscInfo("2",0).match(/\d+/)[0]}catch(f){h=0,light.track("npedit-failure-detection-error",!0)}if(0<h&&1E3>h){light.track("BIZ_CODEBASE_ERR"+h,!0);var e=light.node.build("div",{className:"edit-tips-two-lines",id:"aliedit-tips"});e.html('<div class="edit-tips-text">\u68c0\u6d4b\u4e0d\u5230\u5b89\u5168\u63a7\u4ef6\uff0c\u6682\u4e0d\u80fd\u8f93\u5165\uff0c\u70b9\u6b64<a href="#" target="_blank">\u67e5\u770b\u5e2e\u52a9</a></div><div class="edit-tips-angle"></div>');
e.appendTo(this.options.container);e=document.head||document.getElementsByTagName("head")[0]||document.documentElement;e.getElementsByTagName("link");var d=document.createElement("link");d.setAttribute("charset","utf-8");d.setAttribute("rel","stylesheet");d.setAttribute("href",this.__type.info.cssSrc);e.appendChild(d)}if(c.engine.trident)this.element.attachEvent("onstatechange",function(a,b){if(a=="Error"&&b&&(h=b.match(/(\d+)?.*/)[1])){light.track("BIZ_CODEBASE_EVENT_ERR"+h,true);return false}});
else{var e=this.options.handler.split("."),d=e.length,b=window;if(0!=d)for(var i=0;i<d;i++)b=b[e[i]]=b[e[i]]||{};b.onstatechange=function(a,b){if(a=="Error"&&a=="Warning"&&b&&(h=b.match(/(\d+)?.*/)[1])){light.track("BIZ_CODEBASE_EVENT_ERR"+h,true);return false}}}};return{postInit:function(){if(this.__type.installed){var a=this;this.onready(function(){f.call(a)})}},getInfo:function(a,c,e){var d="",b={4:"mac",5:"ipproxy",Default:"password"}[c];if(!this.__type.installed||!this.element)return"";try{"GetMiscInfo"==
a?d=this.element.GetMiscInfo(c,e):"GetEnInfo"==a&&(d=this.element.GetEnInfo(c,e))}catch(g){return light.track("npedit-"+b+"-interface-error",!0),""}if(3==c){if(1==d)return light.track("npedit-password-is-empty",!0),!1;if(0==d)return!0}if(344==d.length||/XOR_1_0{30}_/.test(d))return d;if(5==c&&""===d)return"";light.track("npedit-"+b+"-invalid",!0);return""},getCi1:function(){return this.getInfo("GetMiscInfo","4",0)},getCi2:function(){return this.getInfo("GetMiscInfo","5",0)},getVersion:function(){return""},
getPassword:function(){return!this.getInfo("GetMiscInfo","3",0)?"":this.getInfo("GetEnInfo","Default",0)}}}(),f=a.npedit=light.deriveFrom(a.base,j,f);f.defaults={};a.refreshStatus(a.npedit);f.installed&&(f.installed=a.edit.installed)}(alipay.security,light.client.storage);
light.has("/security/noedit")||function(a){members={ready:!0,render:function(a){light.isFunction(a)&&this._readyList.push(a);this.element=light.get(this.options.id);for(a=this._readyList;a.length;)a.shift().apply(this)},getPassword:function(){return this.element.value}};a.noedit=light.deriveFrom(a.base,members,{Name:"noedit"})}(alipay.security);window.Tracker&&Tracker.click("alipay.security.edit-1.5.js");