(function (){
  var h=void 0,j=true,k=null,m=false,t,u=this;function aa(a,b){var c=a.split("."),e=u;!(c[0]in e)&&e.execScript&&e.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&b!==h?e[f]=b:e=e[f]?e[f]:e[f]={}}function v(){}
function w(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function y(a){return typeof a=="string"}function ba(a){return w(a)=="function"}function A(a){return a[ca]||(a[ca]=++da)}var ca="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),da=0;function ea(a,b,c){return a.call.apply(a.bind,arguments)}
function fa(a,b,c){if(!a)throw Error();if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}function C(a,b,c){C=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ea:fa;return C.apply(k,arguments)}var ia=Date.now||function(){return+new Date};
function D(a,b){function c(){}c.prototype=b.prototype;a.i=b.prototype;a.prototype=new c;a.prototype.constructor=a}Function.prototype.bind=Function.prototype.bind||function(a,b){if(arguments.length>1){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return C.apply(k,c)}else return C(this,a)};function ja(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}
function ka(a,b){for(var c=0,e=ja(String(a)).split("."),f=ja(String(b)).split("."),d=Math.max(e.length,f.length),g=0;c==0&&g<d;g++){var i=e[g]||"",l=f[g]||"",n=RegExp("(\\d*)(\\D*)","g"),z=RegExp("(\\d*)(\\D*)","g");do{var o=n.exec(i)||["","",""],r=z.exec(l)||["","",""];if(o[0].length==0&&r[0].length==0)break;c=la(o[1].length==0?0:parseInt(o[1],10),r[1].length==0?0:parseInt(r[1],10))||la(o[2].length==0,r[2].length==0)||la(o[2],r[2])}while(c==0)}return c}
function la(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var E=Array.prototype,ma=E.indexOf?function(a,b,c){return E.indexOf.call(a,b,c)}:function(a,b,c){c=c==k?0:c<0?Math.max(0,a.length+c):c;if(y(a))return!y(b)||b.length!=1?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},na=E.forEach?function(a,b,c){E.forEach.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=y(a)?a.split(""):a,d=0;d<e;d++)d in f&&b.call(c,f[d],d,a)};function oa(a,b,c,e){E.splice.apply(a,pa(arguments,1))}
function pa(a,b,c){return arguments.length<=2?E.slice.call(a,b):E.slice.call(a,b,c)};var F,qa,ra,sa;function ta(){return u.navigator?u.navigator.userAgent:k}sa=ra=qa=F=m;var wa;if(wa=ta()){var xa=u.navigator;F=wa.indexOf("Opera")==0;qa=!F&&wa.indexOf("MSIE")!=-1;ra=!F&&wa.indexOf("WebKit")!=-1;sa=!F&&!ra&&xa.product=="Gecko"}var ya=F,G=qa,za=sa,Aa=ra,Ba=u.navigator,Ca=(Ba&&Ba.platform||"").indexOf("Mac")!=-1,Da;
a:{var Ea="",Fa;if(ya&&u.opera)var Ga=u.opera.version,Ea=typeof Ga=="function"?Ga():Ga;else if(za?Fa=/rv\:([^\);]+)(\)|;)/:G?Fa=/MSIE\s+([^\);]+)(\)|;)/:Aa&&(Fa=/WebKit\/(\S+)/),Fa)var Ha=Fa.exec(ta()),Ea=Ha?Ha[1]:"";if(G){var Ia,Ja=u.document;Ia=Ja?Ja.documentMode:h;if(Ia>parseFloat(Ea)){Da=String(Ia);break a}}Da=Ea}var Ka={};function La(a){return Ka[a]||(Ka[a]=ka(Da,a)>=0)}var Ma={};function Na(){return Ma[9]||(Ma[9]=G&&document.documentMode&&document.documentMode>=9)};var Oa;!G||Na();!za&&!G||G&&Na()||za&&La("1.9.1");G&&La("9");function Qa(a){return(a=a.className)&&typeof a.split=="function"?a.split(/\s+/):[]}function H(a,b){for(var c=Qa(a),e=pa(arguments,1),f=c,d=0,g=0;g<e.length;g++)ma(f,e[g])>=0||(f.push(e[g]),d++);a.className=c.join(" ")}function I(a,b){for(var c=Qa(a),e=pa(arguments,1),f=c,d=0,g=0;g<f.length;g++)ma(e,f[g])>=0&&(oa(f,g--,1),d++);a.className=c.join(" ")};function Ra(a,b){for(var c in a)b.call(h,a[c],c,a)}function Sa(){var a=Ta,b;for(b in a)return m;return j}var Ua="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function Va(a,b){for(var c,e,f=1;f<arguments.length;f++){e=arguments[f];for(c in e)a[c]=e[c];for(var d=0;d<Ua.length;d++)c=Ua[d],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};function Wa(a){return y(a)?document.getElementById(a):a}function Xa(a){this.Ba=a||u.document||document};function Ya(){return j};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

 The "New" BSD License:

 Copyright (c) 2005-2009, The Dojo Foundation
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
 may be used to endorse or promote products derived from this software
 without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var J=function(){function a(a,c){if(!a)return[];if(a.constructor==Array)return a;if(!y(a))return[a];if(y(c)&&(c=Wa(c),!c))return[];var c=c||document,d=c.ownerDocument||c.documentElement;U=c.contentType&&c.contentType=="application/xml"||ya&&(c.doctype||d.toString()=="[object XMLDocument]")||!!d&&(G?d.xml:c.xmlVersion||d.xmlVersion);return(d=e(a)(c))&&d.J?d:b(d)}function b(a){if(a&&a.J)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(a.length<2)return b;B++;if(G&&U){var c=B+"";a[0].setAttribute("_zipIdx",
c);for(var e=1,d;d=a[e];e++)a[e].getAttribute("_zipIdx")!=c&&b.push(d),d.setAttribute("_zipIdx",c)}else if(G&&a.za)try{for(e=1;d=a[e];e++)ua(d)&&b.push(d)}catch(f){}else{a[0]&&(a[0]._zipIdx=B);for(e=1;d=a[e];e++)a[e]._zipIdx!=B&&b.push(d),d._zipIdx=B}return b}function c(a,b){if(!b)return 1;var c=Sb(a);return!b[c]?b[c]=1:0}function e(a,b){if(pb){var c=qb[a];if(c&&!b)return c}if(c=rb[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");a.indexOf("#")>=0&&d&&(b=j);if(pb&&!b&&">~+".indexOf(c)==-1&&(!G||
a.indexOf(":")==-1)&&!(sb&&a.indexOf(".")>=0)&&a.indexOf(":contains")==-1&&a.indexOf("|=")==-1){var g=">~+".indexOf(a.charAt(a.length-1))>=0?a+" *":a;return qb[a]=function(b){try{if(!(9==b.nodeType||d))throw"";var c=b.querySelectorAll(g);G?c.za=j:c.J=j;return c}catch(S){return e(a,j)(b)}}}else{var i=a.split(/\s*,\s*/);return rb[a]=i.length<2?f(a):function(a){for(var b=0,c=[],e;e=i[b++];)c=c.concat(f(e)(a));return c}}}function f(a){var b=tb(ja(a));if(b.length==1){var c=d(b[0]);return function(a){if(a=
c(a,[]))a.J=j;return a}}return function(a){for(var a=V(a),c,e,Rb=b.length,f,T,g=0;g<Rb;g++){T=[];c=b[g];e=a.length-1;if(e>0)f={},T.J=j;e=d(c);for(var i=0;c=a[i];i++)e(c,T,f);if(!T.length)break;a=T}return T}}function d(a){var b=ub[a.w];if(b)return b;var c=a.la,c=c?c.L:"",e=n(a,{q:1}),d="*"==a.a,f=document.getElementsByClassName;if(c){f={q:1};if(d)f.a=1;e=n(a,f);"+"==c?b=l(e):"~"==c?b=i(e):">"==c&&(b=g(e))}else if(a.id)e=!a.na&&d?Ya:n(a,{q:1,id:1}),b=function(b,c){var d;d=b?new Xa(b.nodeType==9?b:b.ownerDocument||
b.document):Oa||(Oa=new Xa);var f=a.id;if((d=y(f)?d.Ba.getElementById(f):f)&&e(d))if(9==b.nodeType)return V(d,c);else{for(f=d.parentNode;f;){if(f==b)break;f=f.parentNode}if(f)return V(d,c)}};else if(f&&/\{\s*\[native code\]\s*\}/.test(String(f))&&a.g.length&&!sb)var e=n(a,{q:1,g:1,id:1}),r=a.g.join(" "),b=function(a,b){for(var c=V(0,b),d,f=0,S=a.getElementsByClassName(r);d=S[f++];)e(d,a)&&c.push(d);return c};else!d&&!a.na?b=function(b,c){for(var e=V(0,c),d,f=0,S=b.getElementsByTagName(a.W());d=S[f++];)e.push(d);
return e}:(e=n(a,{q:1,a:1,id:1}),b=function(b,c){for(var d=V(0,c),f,S=0,g=b.getElementsByTagName(a.W());f=g[S++];)e(f,b)&&d.push(f);return d});return ub[a.w]=b}function g(a){a=a||Ya;return function(b,e,d){for(var f=0,g=b[vb];b=g[f++];)ga(b)&&(!d||c(b,d))&&a(b,f)&&e.push(b);return e}}function i(a){return function(b,e,d){for(b=b[ha];b;){if(ga(b)){if(d&&!c(b,d))break;a(b)&&e.push(b)}b=b[ha]}return e}}function l(a){return function(b,e,d){for(;b=b[ha];)if(!va||ua(b)){(!d||c(b,d))&&a(b)&&e.push(b);break}return e}}
function n(a,b){if(!a)return Ya;var b=b||{},c=k;b.q||(c=W(c,ua));b.a||a.a!="*"&&(c=W(c,function(b){return b&&b.tagName==a.W()}));b.g||na(a.g,function(a,b){var e=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=W(c,function(a){return e.test(a.className)});c.Ja=b});b.m||na(a.m,function(a){var b=a.name;Pa[b]&&(c=W(c,Pa[b](b,a.value)))});b.G||na(a.G,function(a){var b,e=a.S;a.type&&wb[a.type]?b=wb[a.type](e,a.$):e.length&&(b=Tb(e));b&&(c=W(c,b))});b.id||a.id&&(c=W(c,function(b){return!!b&&b.id==a.id}));c||"default"in
b||(c=Ya);return c}function z(a){return r(a)%2}function o(a){return!(r(a)%2)}function r(a){var b=a.parentNode,c=0,e=b[vb],d=a._i||-1,f=b._l||-1;if(!e)return-1;e=e.length;if(f==e&&d>=0&&f>=0)return d;b._l=e;d=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[ha])if(ga(b))b._i=++c,a===b&&(d=c);return d}function q(a){for(;a=a[ha];)if(ga(a))return m;return j}function xb(a){for(;a=a[Ub];)if(ga(a))return m;return j}function X(a,b){return!a?"":b=="class"?a.className||"":b=="for"?a.htmlFor||"":b=="style"?
a.style.cssText||"":(U?a.getAttribute(b):a.getAttribute(b,2))||""}function ua(a){return 1==a.nodeType}function W(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function tb(a){function b(){if(r>=0)p.id=c(r,s).replace(/\\/g,""),r=-1;if(n>=0){var a=n==s?k:c(n,s);">~+".indexOf(a)<0?p.a=a:p.L=a;n=-1}l>=0&&(p.g.push(c(l+1,s).replace(/\\/g,"")),l=-1)}function c(b,e){return ja(a.slice(b,e))}a+=">~+".indexOf(a.slice(-1))>=0?" * ":" ";for(var e=[],d=-1,f=-1,g=-1,
i=-1,l=-1,r=-1,n=-1,o="",q="",z,s=0,B=a.length,p=k,x=k;o=q,q=a.charAt(s),s<B;s++)if(o!="\\")if(p||(z=s,p={w:k,m:[],G:[],g:[],a:k,L:k,id:k,W:function(){return U?this.Ea:this.a}},n=s),d>=0)if(q=="]"){x.S?x.$=c(g||d+1,s):x.S=c(d+1,s);if((d=x.$)&&(d.charAt(0)=='"'||d.charAt(0)=="'"))x.$=d.slice(1,-1);p.G.push(x);x=k;d=g=-1}else{if(q=="=")g="|~^$*".indexOf(o)>=0?o:"",x.type=g+q,x.S=c(d+1,s-g.length),g=s+1}else if(f>=0){if(q==")"){if(i>=0)x.value=c(f+1,s);i=f=-1}}else if(q=="#")b(),r=s+1;else if(q==".")b(),
l=s;else if(q==":")b(),i=s;else if(q=="[")b(),d=s,x={};else if(q=="(")i>=0&&(x={name:c(i+1,s),value:k},p.m.push(x)),f=s;else if(q==" "&&o!=q){b();i>=0&&p.m.push({name:c(i+1,s)});p.na=p.m.length||p.G.length||p.g.length;p.Ma=p.w=c(z,s);p.Ea=p.a=p.L?k:p.a||"*";if(p.a)p.a=p.a.toUpperCase();if(e.length&&e[e.length-1].L)p.la=e.pop(),p.w=p.la.w+" "+p.w;e.push(p);p=k}return e}function V(a,b){var c=b||[];a&&c.push(a);return c}var sb=Aa&&document.compatMode=="BackCompat",vb=document.firstChild.children?"children":
"childNodes",U=m,wb={"*=":function(a,b){return function(c){return X(c,a).indexOf(b)>=0}},"^=":function(a,b){return function(c){return X(c,a).indexOf(b)==0}},"$=":function(a,b){return function(c){c=" "+X(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return(" "+X(b,a)+" ").indexOf(c)>=0}},"|=":function(a,b){b=" "+b;return function(c){c=" "+X(c,a);return c==b||c.indexOf(b+"-")==0}},"=":function(a,b){return function(c){return X(c,a)==b}}},va=typeof document.firstChild.nextElementSibling==
"undefined",ha=!va?"nextElementSibling":"nextSibling",Ub=!va?"previousElementSibling":"previousSibling",ga=va?ua:Ya,Pa={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return xb},"last-child":function(){return q},"only-child":function(){return function(a){return!xb(a)?m:!q(a)?m:j}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;a>=0;a--){var c=b[a].nodeType;if(c===1||c==3)return m}return j}},contains:function(a,
b){var c=b.charAt(0);if(c=='"'||c=="'")b=b.slice(1,-1);return function(a){return a.innerHTML.indexOf(b)>=0}},not:function(a,b){var c=tb(b)[0],e={q:1};if(c.a!="*")e.a=1;if(!c.g.length)e.g=1;var d=n(c,e);return function(a){return!d(a)}},"nth-child":function(a,b){if(b=="odd")return z;else if(b=="even")return o;if(b.indexOf("n")!=-1){var c=b.split("n",2),e=c[0]?c[0]=="-"?-1:parseInt(c[0],10):1,d=c[1]?parseInt(c[1],10):0,f=0,g=-1;e>0?d<0?d=d%e&&e+d%e:d>0&&(d>=e&&(f=d-d%e),d%=e):e<0&&(e*=-1,d>0&&(g=d,d%=
e));if(e>0)return function(a){a=r(a);return a>=f&&(g<0||a<=g)&&a%e==d};else b=d}var i=parseInt(b,10);return function(a){return r(a)==i}}},Tb=G?function(a){var b=a.toLowerCase();b=="class"&&(a="className");return function(c){return U?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},ub={},rb={},qb={},pb=!!document.querySelectorAll&&(!Aa||La("526")),B=0,Sb=G?function(a){return U?a.getAttribute("_uid")||a.setAttribute("_uid",++B)||B:a.uniqueID}:
function(a){return a._uid||(a._uid=++B)};a.m=Pa;return a}();aa("goog.dom.query",J);aa("goog.dom.query.pseudos",J.m);var Za;!G||Na();var $a=G&&!La("8");function K(){}K.prototype.ha=m;K.prototype.p=function(){if(!this.ha)this.ha=j,this.e()};K.prototype.e=function(){this.Aa&&ab.apply(k,this.Aa)};function ab(a){for(var b=0,c=arguments.length;b<c;++b){var e=arguments[b],f=w(e);f=="array"||f=="object"&&typeof e.length=="number"?ab.apply(k,e):e&&typeof e.p=="function"&&e.p()}};function L(a,b){this.type=a;this.currentTarget=this.target=b}D(L,K);L.prototype.e=function(){delete this.type;delete this.target;delete this.currentTarget};L.prototype.v=m;L.prototype.F=j;L.prototype.preventDefault=function(){this.F=m};function bb(a){bb[" "](a);return a}bb[" "]=v;function M(a,b){a&&this.H(a,b)}D(M,L);t=M.prototype;t.target=k;t.relatedTarget=k;t.offsetX=0;t.offsetY=0;t.clientX=0;t.clientY=0;t.screenX=0;t.screenY=0;t.button=0;t.keyCode=0;t.charCode=0;t.ctrlKey=m;t.altKey=m;t.shiftKey=m;t.metaKey=m;t.Fa=m;t.T=k;
t.H=function(a,b){var c=this.type=a.type;L.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;if(e){if(za){var f;a:{try{bb(e.nodeName);f=j;break a}catch(d){}f=m}f||(e=k)}}else if(c=="mouseover")e=a.fromElement;else if(c=="mouseout")e=a.toElement;this.relatedTarget=e;this.offsetX=a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=
a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.Fa=Ca?a.metaKey:a.ctrlKey;this.state=a.state;this.T=a;delete this.F;delete this.v};
t.preventDefault=function(){M.i.preventDefault.call(this);var a=this.T;if(a.preventDefault)a.preventDefault();else if(a.returnValue=m,$a)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}};t.e=function(){M.i.e.call(this);this.relatedTarget=this.currentTarget=this.target=this.T=k};function cb(){}var db=0;t=cb.prototype;t.key=0;t.z=m;t.da=m;t.H=function(a,b,c,e,f,d){if(ba(a))this.ma=j;else if(a&&a.handleEvent&&ba(a.handleEvent))this.ma=m;else throw Error("Invalid listener argument");this.C=a;this.ta=b;this.src=c;this.type=e;this.capture=!!f;this.X=d;this.da=m;this.key=++db;this.z=m};t.handleEvent=function(a){return this.ma?this.C.call(this.X||this.src,a):this.C.handleEvent.call(this.C,a)};function N(a,b){this.oa=b;this.l=[];if(a>this.oa)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var c=0;c<a;c++)this.l.push(this.h?this.h():{})}D(N,K);N.prototype.h=k;N.prototype.ga=k;function eb(a){return a.l.length?a.l.pop():a.h?a.h():{}}function fb(a,b){a.l.length<a.oa?a.l.push(b):gb(a,b)}function gb(a,b){if(a.ga)a.ga(b);else{var c=w(b);if(c=="object"||c=="array"||c=="function")if(ba(b.p))b.p();else for(var e in b)delete b[e]}}
N.prototype.e=function(){N.i.e.call(this);for(var a=this.l;a.length;)gb(this,a.pop());delete this.l};var hb,ib=(hb="ScriptEngine"in u&&u.ScriptEngine()=="JScript")?u.ScriptEngineMajorVersion()+"."+u.ScriptEngineMinorVersion()+"."+u.ScriptEngineBuildVersion():"0";var jb,kb,lb,mb,nb,ob,yb,zb,Ab,Bb,Cb;
(function(){function a(){return{d:0,c:0}}function b(){return[]}function c(){function a(b){b=g.call(a.src,a.key,b);if(!b)return b}return a}function e(){return new cb}function f(){return new M}var d=hb&&!(ka(ib,"5.7")>=0),g;ob=function(a){g=a};if(d){jb=function(){return eb(i)};kb=function(a){fb(i,a)};lb=function(){return eb(l)};mb=function(a){fb(l,a)};nb=function(){return eb(n)};yb=function(){fb(n,c())};zb=function(){return eb(z)};Ab=function(a){fb(z,a)};Bb=function(){return eb(o)};Cb=function(a){fb(o,
a)};var i=new N(0,600);i.h=a;var l=new N(0,600);l.h=b;var n=new N(0,600);n.h=c;var z=new N(0,600);z.h=e;var o=new N(0,600);o.h=f}else jb=a,kb=v,lb=b,mb=v,nb=c,yb=v,zb=e,Ab=v,Bb=f,Cb=v})();var O={},P={},Q={},Db={};
function R(a,b,c,e,f){if(b)if(w(b)=="array")for(var d=0;d<b.length;d++)R(a,b[d],c,e,f);else{var e=!!e,g=P;b in g||(g[b]=jb());g=g[b];e in g||(g[e]=jb(),g.d++);var g=g[e],i=A(a),l;g.c++;if(g[i]){l=g[i];for(d=0;d<l.length;d++)if(g=l[d],g.C==c&&g.X==f){if(g.z)break;return}}else l=g[i]=lb(),g.d++;d=nb();d.src=a;g=zb();g.H(c,d,a,b,e,f);c=g.key;d.key=c;l.push(g);O[c]=g;Q[i]||(Q[i]=lb());Q[i].push(g);a.addEventListener?(a==u||!a.fa)&&a.addEventListener(b,d,e):a.attachEvent(b in Db?Db[b]:Db[b]="on"+b,d)}else throw Error("Invalid event type");
}function Eb(a,b,c,e,f){if(w(b)=="array")for(var d=0;d<b.length;d++)Eb(a,b[d],c,e,f);else{e=!!e;a:{d=P;if(b in d&&(d=d[b],e in d&&(d=d[e],a=A(a),d[a]))){a=d[a];break a}a=k}if(a)for(d=0;d<a.length;d++)if(a[d].C==c&&a[d].capture==e&&a[d].X==f){Fb(a[d].key);break}}}
function Fb(a){if(O[a]){var b=O[a];if(!b.z){var c=b.src,e=b.type,f=b.ta,d=b.capture;c.removeEventListener?(c==u||!c.fa)&&c.removeEventListener(e,f,d):c.detachEvent&&c.detachEvent(e in Db?Db[e]:Db[e]="on"+e,f);c=A(c);f=P[e][d][c];if(Q[c]){var g=Q[c],i=ma(g,b);i>=0&&E.splice.call(g,i,1);g.length==0&&delete Q[c]}b.z=j;f.qa=j;Gb(e,d,c,f);delete O[a]}}}
function Gb(a,b,c,e){if(!e.I&&e.qa){for(var f=0,d=0;f<e.length;f++)if(e[f].z){var g=e[f].ta;g.src=k;yb(g);Ab(e[f])}else f!=d&&(e[d]=e[f]),d++;e.length=d;e.qa=m;d==0&&(mb(e),delete P[a][b][c],P[a][b].d--,P[a][b].d==0&&(kb(P[a][b]),delete P[a][b],P[a].d--),P[a].d==0&&(kb(P[a]),delete P[a]))}}
function Hb(a){var b,c=0,e=b==k;b=!!b;if(a==k)Ra(Q,function(a){for(var d=a.length-1;d>=0;d--){var f=a[d];if(e||b==f.capture)Fb(f.key),c++}});else if(a=A(a),Q[a])for(var a=Q[a],f=a.length-1;f>=0;f--){var d=a[f];if(e||b==d.capture)Fb(d.key),c++}}function Ib(a,b,c,e,f){var d=1,b=A(b);if(a[b]){a.c--;a=a[b];a.I?a.I++:a.I=1;try{for(var g=a.length,i=0;i<g;i++){var l=a[i];l&&!l.z&&(d&=Jb(l,f)!==m)}}finally{a.I--,Gb(c,e,b,a)}}return Boolean(d)}
function Jb(a,b){var c=a.handleEvent(b);a.da&&Fb(a.key);return c}
ob(function(a,b){if(!O[a])return j;var c=O[a],e=c.type,f=P;if(!(e in f))return j;var f=f[e],d,g;Za===h&&(Za=G&&!u.addEventListener);if(Za){var i;if(!(i=b))a:{i="window.event".split(".");for(var l=u;d=i.shift();)if(l[d]!=k)l=l[d];else{i=k;break a}i=l}d=i;i=j in f;l=m in f;if(i){if(d.keyCode<0||d.returnValue!=h)return j;a:{var n=m;if(d.keyCode==0)try{d.keyCode=-1;break a}catch(z){n=j}if(n||d.returnValue==h)d.returnValue=j}}n=Bb();n.H(d,this);d=j;try{if(i){for(var o=lb(),r=n.currentTarget;r;r=r.parentNode)o.push(r);
g=f[j];g.c=g.d;for(var q=o.length-1;!n.v&&q>=0&&g.c;q--)n.currentTarget=o[q],d&=Ib(g,o[q],e,j,n);if(l){g=f[m];g.c=g.d;for(q=0;!n.v&&q<o.length&&g.c;q++)n.currentTarget=o[q],d&=Ib(g,o[q],e,m,n)}}else d=Jb(c,n)}finally{if(o)o.length=0,mb(o);n.p();Cb(n)}return d}e=new M(b,this);try{d=Jb(c,e)}finally{e.p()}return d});function Kb(){}D(Kb,K);t=Kb.prototype;t.fa=j;t.ba=k;t.addEventListener=function(a,b,c,e){R(this,a,b,c,e)};t.removeEventListener=function(a,b,c,e){Eb(this,a,b,c,e)};
t.dispatchEvent=function(a){var b=a.type||a,c=P;if(b in c){if(y(a))a=new L(a,this);else if(a instanceof L)a.target=a.target||this;else{var e=a,a=new L(b,this);Va(a,e)}var e=1,f,c=c[b],b=j in c,d;if(b){f=[];for(d=this;d;d=d.ba)f.push(d);d=c[j];d.c=d.d;for(var g=f.length-1;!a.v&&g>=0&&d.c;g--)a.currentTarget=f[g],e&=Ib(d,f[g],a.type,j,a)&&a.F!=m}if(m in c)if(d=c[m],d.c=d.d,b)for(g=0;!a.v&&g<f.length&&d.c;g++)a.currentTarget=f[g],e&=Ib(d,f[g],a.type,m,a)&&a.F!=m;else for(f=this;!a.v&&f&&d.c;f=f.ba)a.currentTarget=
f,e&=Ib(d,f,a.type,m,a)&&a.F!=m;a=Boolean(e)}else a=j;return a};t.e=function(){Kb.i.e.call(this);Hb(this);this.ba=k};var Lb=u.window;function Mb(a){if(!ba(a))if(a&&typeof a.handleEvent=="function")a=C(a.handleEvent,a);else throw Error("Invalid listener argument");return Lb.setTimeout(a,20)};var Ta={},Nb=k;function Ob(a){a=A(a);delete Ta[a];Sa()&&Nb&&(Lb.clearTimeout(Nb),Nb=k)}function Pb(){Nb||(Nb=Mb(function(){Qb()}))}function Qb(){var a=ia();Nb=k;Ra(Ta,function(b){Vb(b,a)});Sa()||Pb()};function Wb(a,b,c,e){if(w(a)!="array"||w(b)!="array")throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.Ca=b;this.duration=c;this.ca=e;this.coords=[]}D(Wb,Kb);t=Wb.prototype;t.f=0;t.ja=0;t.b=0;t.startTime=k;t.ia=k;t.Z=k;
t.play=function(a){if(a||this.f==0)this.b=0,this.coords=this.A;else if(this.f==1)return m;Ob(this);this.startTime=a=ia();this.f==-1&&(this.startTime-=this.duration*this.b);this.ia=this.startTime+this.duration;this.Z=this.startTime;this.b||this.D();Y(this,"play");this.f==-1&&Y(this,"resume");this.f=1;var b=A(this);b in Ta||(Ta[b]=this);Pb();Vb(this,a);return j};t.stop=function(a){Ob(this);this.f=0;if(a)this.b=1;Xb(this,this.b);Y(this,"stop");this.K()};
t.e=function(){this.f!=0&&this.stop(m);Y(this,"destroy");Wb.i.e.call(this)};function Vb(a,b){a.b=(b-a.startTime)/(a.ia-a.startTime);if(a.b>=1)a.b=1;a.ja=1E3/(b-a.Z);a.Z=b;Xb(a,a.b);a.b==1?(a.f=0,Ob(a),Y(a,"finish"),a.K()):a.f==1&&a.aa()}function Xb(a,b){ba(a.ca)&&(b=a.ca(b));a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.Ca[c]-a.A[c])*b+a.A[c]}t.aa=function(){Y(this,"animate")};t.D=function(){Y(this,"begin")};t.K=function(){Y(this,"end")};
function Y(a,b){a.dispatchEvent(new Yb(b,a))}function Yb(a,b){L.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.Na=b.coords[2];this.duration=b.duration;this.b=b.b;this.La=b.ja;this.state=b.f;this.Ia=b}D(Yb,L);function Z(a,b,c,e,f){Wb.call(this,b,c,e,f);this.element=a}D(Z,Wb);Z.prototype.Q=v;Z.prototype.aa=function(){this.Q();Z.i.aa.call(this)};Z.prototype.K=function(){this.Q();Z.i.K.call(this)};Z.prototype.D=function(){this.Q();Z.i.D.call(this)};function Zb(a,b,c,e,f){if(b.length!=2||c.length!=2)throw Error("Start and end points must be 2D");Z.apply(this,arguments)}D(Zb,Z);
Zb.prototype.Q=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};function $b(a,b,c,e){Zb.call(this,a,[a.offsetLeft,a.offsetTop],b,c,e)}D($b,Zb);$b.prototype.D=function(){this.A=[this.element.offsetLeft,this.element.offsetTop];$b.i.D.call(this)};function ac(a){return 1-Math.pow(1-a,3)};function $(a){this.n=Wa(a.scrollerId);this.Ga=Wa(a.slidesContainerId);this.j=J("ul",this.n)[0];this.Da=a.oneAtATimeFlag;this.ya=a.centerFlag;this.ua=a.randomFlag;this.va=a.selectItemCallback;this.k=J("ul li",this.n)[0].scrollWidth;this.P=Math.ceil(this.j.parentNode.offsetWidth/this.k);this.j.parentNode.style.overflow="hidden";this.sa=this.k*this.P;this.u=J(".g-scroller-controls .g-scroller-previous",this.n)[0];this.t=J(".g-scroller-controls .g-scroller-next",this.n)[0];this.ka=this.B=m;this.r=[];
this.s={};bc(this);this.M=this.k*this.P-this.xa;H(this.t,"disabled-next");H(this.u,"disabled-prev");R(this.t,"click",function(a){this.scroll("right");a.preventDefault()},k,this);R(this.u,"click",function(a){this.scroll("left");a.preventDefault()},k,this);R(this.n,"keyup",function(a){switch(a.keyCode){case 37:var b=this.wa.index-1;break;case 39:b=this.wa.index+1}(a=this.s[this.r[b]])&&this.N(a)},k,this);var b=this.V(location.href);this.ua&&!b&&(b=this.r[Math.floor(Math.random()*this.r.length)]);!a.defaultItem&&
!b&&!this.ua&&(b=this.r[0]);this.N(this.Y(b)?b:this.Y(a.defaultItem)?a.defaultItem:this.s[this.r[0]])}function bc(a){var b=a.n.getElementsByTagName("a"),c=b.length;a.xa=a.k*(c-2);a.j.style.width=a.xa+"px";for(var e=2,f=0;e<c;e++,f++){var d=b[e],g=a.V(d.href),i=Wa(g);a.s[g]={};var l=a.s[g];l.index=f;l.O=i;l.Ha=d;l.id=g;l.ra=Math.ceil((f+1)/a.P);a.pa=l.ra;a.r.push(l.id);if(l.O)l.O.id=g+"_scroller",H(i,"hidden");R(d,"click",C(a.N,a,l))}}t=$.prototype;
t.N=function(a,b){typeof a=="string"&&(a=this.U(a));b&&b.preventDefault();for(var c=J(".g-scroller-viewport a.selected",this.n),e=J(".g-scroller-slide",this.Ga),f=0,d=c.length;f<d;f++)I(c[f],"selected");f=0;for(d=e.length;f<d;f++)H(e[f],"hidden");H(a.Ha,"selected");a.O&&I(a.O,"hidden");this.ya&&this.ea(a);this.wa=a;this.o=a.ra;location.hash?this.ka&&window.location.replace(location.toString().replace(location.hash,"#"+a.id)):window.location.replace(location.toString()+"#"+a.id);this.va&&this.va(a);
this.ka=j};t.scroll=function(a){if(this.Da)a=a=="right"?this.j.offsetLeft-this.k:this.j.offsetLeft+this.k;else if(a=="right"){if(a=this.j.offsetLeft-this.sa,!this.B&&(this.o++,this.o>this.pa))this.o=this.pa}else if(a=this.j.offsetLeft+this.sa,!this.B&&(this.o--,this.o<1))this.o=1;this.R(a)};t.U=function(a){return this.s[a]};
t.R=function(a){a>=0?(a=0,H(this.u,"disabled-prev"),I(this.t,"disabled-next")):a<=this.M||I(this.u,"disabled-prev");a<=this.M?(a=this.M,H(this.t,"disabled-next"),I(this.u,"disabled-prev")):I(this.t,"disabled-next");a>=0&&a<=this.M&&(H(this.t,"disabled-next"),H(this.u,"disabled-prev"));if(!this.B)this.B=j,this.Ka=a,a=new $b(this.j,[a,this.j.offsetTop],400,ac),R(a,"end",C(function(){this.B=m},this)),a.play()};
t.ea=function(a){typeof a=="string"&&(a=this.U(a));this.R(Math.floor(this.P/2)*this.k-a.index*this.k)};t.V=function(a){return(a=/#([^&]*)/.exec(a))?a[1]:k};t.Y=function(a){return a in this.s};aa("gweb.ui.Scroller",$);$.prototype.selectItem=$.prototype.N;$.prototype.scroll=$.prototype.scroll;$.prototype.getItemFromId=$.prototype.U;$.prototype.animateToPosition=$.prototype.R;$.prototype.centerOnItem=$.prototype.ea;$.prototype.getStringAfterHash=$.prototype.V;$.prototype.isValidItem=$.prototype.Y;
})()