splashRadar._JSINIT=!0;splashRadar._JSINITTime=(new Date).getTime();splashRadar._JSLOADTime=(new Date).getTime()-splashRadar._JSLOADTime;splashRadar("JSLoad",1);splashRadar("JSInit");
(function(a){function b(b,f){var c=a.m$portal.cookie,d,p,w=RegExp("(^|\\|)("+b+"=)(.*?)(\\||$)");if(b)return d=c("s")||"",p=(d.match(w)||[])[3],void 0!==f?c("s",p||null===f?d.replace(w,null===f?function(b,a,f,c,d,h,e){return 0===e.indexOf(b)?"":d}:"$1$2"+f+"$4"):(d?d+"|":"")+b+"="+f,{domain:".mail.ru",expires:365,path:"/"}):f=p,f}var c={splash:"s",news:"n",afisha:"a",auto:"av",lady:"l",horo:"h",pogoda:"p",mail:"m",promail:"pm",blogs:"b",foto:"f",video:"v",my:"my",agent:"ag",torg:"t",love:"lv",game:"g",
"hi-tech":"ht",maps:"map"},f,d=a.m$portal;d||(d=a.m$portal={});d.S_Cookie=function(a){f||(a=c[a],f=new function(){function f(){throw Error("project must be set");}function c(d){a||f();return b(a+"_"+d)}this.getLocal=c;this.setLocal=function(d,p){a||f();if(void 0==p)throw Error("need value");b(a+"_"+d,p);return c(d)};this.removeLocal=function(d){a||f();var p=c(d);b(a+"_"+d,null);return p};this.getGlobal=function(a){return b(a)};this.setGlobal=function(a,f){if(void 0==f)throw Error("need value");b(a,
f);return b(a)};this.removeGlobal=function(a){var f=b(a);b(a,null);return f}});return f}})(window);Splash.getUniqueId=function(){var a=0;return function(){return a++}}();
extend(mr,{getLf1Url:function(a,b){var b=(b||location.href).replace(/https?:\/\/(\S+\.)*?mail.ru/i,"//lf1.mail.ru"),c=-1===b.indexOf("?")?"?":"&";if(a)for(var f in a)a.hasOwnProperty(f)&&(b+=c+f+"="+encodeURIComponent(a[f]),c="&");return b},tag:function(a,b,c){if(c&&document.querySelectorAll)return(b||document).querySelectorAll(a+"."+c);a=(b||document).getElementsByTagName(a);if(c){for(var b=[],f=0;f<a.length;f++){var d=a[f];mr.hasClass(d,c)&&b.push(d)}return b}return a},toggleClass:function(a,b,
c,f){!1===f||void 0===f&&mr.hasClass(a,b)?(mr.removeClass(a,b),c&&mr.addClass(a,c)):(mr.addClass(a,b),c&&mr.removeClass(a,c))},hasParent:function(a,b){var c;c=mr.isNode(b)?function(a,b){return a==b}:function(a,b){return mr.hasClass(a,b)};for(var f=a.parentNode;f;){if(c(f,b))return f;f=f.parentNode}return!1},isNode:function(a){return a&&1==a.nodeType},preventDefault:function(a){a&&a.preventDefault?a.preventDefault():window.event.returnValue=!1},s_cookie:m$portal.S_Cookie("splash"),data:function(a,
b,c){if(!a)return null;if(void 0===c)return a.getAttribute("data-"+b);a.setAttribute("data-"+b,c)},proxy:function(a,b){return function(){return a.apply(b,arguments)}},position:function(a){if(a.getBoundingClientRect){var a=a.getBoundingClientRect(),b=document.body,c=document.documentElement;return{left:a.left+(window.pageXOffset||c.scrollLeft||b.scrollLeft)-(c.clientLeft||b.clientLeft||0),top:a.top+(window.pageYOffset||c.scrollTop||b.scrollTop)-(c.clientTop||b.clientTop||0)}}b=parseFloat(a.offsetTop);
for(c=parseFloat(a.offsetLeft);a=a.offsetParent;)b+=parseFloat(a.offsetTop),c+=parseFloat(a.offsetLeft);return{left:c,top:b}},getJson:function(a,b,c,f){new Ajax(a,{json:!0,params:b,callback:c,error:f})},_jsonpId:0,JSONP:function(a){var b=a.url,c=a.params,f=a.getName||"callback",d=a.callback,h=a.error,a=a.timeout,e=document.createElement("script"),k="__jsonp_"+mr._jsonpId++;window[k]=function(a){clearTimeout(e._timeout);d(a)};a&&(e._timeout=setTimeout(function(){h()},a));c||(c={});c[f]=k;c.rnd=(new Date).getTime()+
Math.random();c=mr.formatQuery(c);e.src=b+(0<b.indexOf("?")?"&":"?")+c;document.getElementsByTagName("head")[0].appendChild(e)},formatQuery:function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return b.join("&")},parseJson:function(a){if("string"!==typeof a||!a)return null;try{return window.JSON&&window.JSON.parse?window.JSON.parse(a):(new Function("return "+a))()}catch(b){return window.logError&&logError(b,"parseJson"),null}},plural:function(a){return 1==
a%10&&11!=a%100?0:2<=a%10&&4>=a%10&&(10>a%100||20<=a%100)?1:2},placeSlot:function(a){var b=mr.id("slot_"+a),a=mr.id("placeholder_"+a);b&&a&&(a.innerHTML=b.innerHTML)},placeSlots:function(){for(var a=0;a<arguments.length;a++)mr.placeSlot(arguments[a])},extendClass:function(a,b){var c=function(){};c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a}});
function Ajax(a,b){var c=this.getTransport();if(c){var f=b.method||"get",d=b.json||!1,h=b.params||{},e=b.callback||function(){},k=b.error||function(){};"get"==f&&b.params&&(a+=(-1!=a.indexOf("?")?"&":"?")+mr.formatQuery(h));c.onreadystatechange=function(){var a;if(4===c.readyState){if(200===c.status)if(d){var b;try{b=mr.parseJson(c.responseText)}catch(f){window.logError&&logError(f,"readyState"),a=f,window.console&&window.console.error&&console.error(f)}a||e(b)}else e(c.responseText);if(200!==c.status||
a)k(a instanceof Error&&a||Error("request error"))}};c.open(f,a,!0);c.send("get"==f?null:mr.formatQuery(h))}}Ajax.prototype={getTransport:window.ActiveXObject&&!window.XMLHttpRequest?function(){try{return new window.ActiveXObject("Microsoft.XMLHTTP")}catch(a){window.logError&&logError(a,"getTransport_IE")}}:function(){try{return new window.XMLHttpRequest}catch(a){window.logError&&logError(a,"getTransport_XHR")}}};
(function(){function a(a){this._context=a||this;this._mixedIn=[]}function b(a,b,d){this.eventName=a;this.target=b;this.data=d}a.prototype.emit=function(a,f){var d;if(!this._events||!this._events[a]||!(d=this._events[a]))return!1;for(var h=0,e=d.length;h<e;h++){var k=d[h];"function"===typeof k&&k.apply(this._context,[new b(a,this._context,f)])}return!0};a.prototype.addListener=function(a,b){if("function"!==typeof b)throw Error("invalid argument");this._events||(this._events={});this._events[a]||(this._events[a]=
[]);this._events[a].push(b);return this};a.prototype.on=a.prototype.addListener;a.prototype.once=function(a,b){function d(){this.removeListener(a,d);b.apply(this._context,arguments)}if("function"!==typeof b)throw Error("invalid argument");this.on(a,d);return this};a.prototype.removeListener=function(a,b){if("function"!==typeof b)throw Error("invalid argument");if(!this._events[a])return this;var d=this._events[a],h=d.indexOf(b);if(0>h)return this;d.splice(h,1);0===d.length&&delete this._events[a];
return this};a.prototype.mixin=function(a){a.bind=this.bind.bind(this);a.unbind=this.unbind.bind(this);a.dispatch=this.dispatch.bind(this);this._mixedIn.push(a)};a.prototype.bind=function(a,b){this.on(a,b);return this};a.prototype.unbind=function(a,b){this.removeListener(a,b)};a.prototype.dispatch=function(a,b){this.emit.apply(this,arguments)};a.prototype.destroy=function(){for(var a=0,b=this._mixedIn.length;a<b;a++){var d=this._mixedIn[a];d.bind=d.unbind=d.dispatch=void 0}this._mixedIn=this._events=
this._context=void 0};Splash.EventEmitter=a})();
(function(){function a(a,b,c){this._elem=a;this._name=b;this._fn=c;this._attached=!1;this._handler=mr.proxy(this._fn,this)}var b=0,c={};a.addListener=function(f,d,h){if(Array.prototype.isArray(f)){for(var e=0,k=f.length;e<k;e++)f[e]&&a.addListener(f[e],d,h);return this}d=Array.prototype.isArray(d)?d:[d];e=!1;h.uuid&&(e=!0);var q=h.uuid||b;h.uuid=q;q=c[q]=function(a){var a=Event._fix(a||window.event),b=h.call(f,a);!1===b&&(a.preventDefault(),a.stopPropagation());return b};e||b++;e=0;for(k=d.length;e<
k;e++)document.addEventListener?f.addEventListener(d[e],q,!1):f.attachEvent("on"+d[e],q);return this};a.on=a.addListener;a.removeListener=function(b,d,h){if(Array.prototype.isArray(b)){for(var e=0,k=b.length;e<k;e++)b[e]&&a.removeListener(b[e],d,h);return this}d=Array.prototype.isArray(d)?d:[d];e=0;for(k=d.length;e<k;e++)document.removeEventListener?b.removeEventListener(d[e],c[h.uuid],!1):b.detachEvent("on"+d[e],c[h.uuid]);return this};a.once=function(b,d,c){function e(k){c.call(this,k);a.removeListener(b,
d,e)}this.on(b,d,e);return this};a.prototype={attach:function(){this._attached||(this._attached=!0,this._attach())},detach:function(){this._attached&&(this._detach(),this._attached=!1)},_attach:function(){a.on(this._elem,this._name,this._handler)},_detach:function(){a.removeListener(this._elem,this._name,this._handler)},destroy:function(){this.detach();this._elem=this._name=this._fn=this._handler=null}};Event={_fixHooks:{key:{props:["charCode","keyCode"],fix:function(a,b){a.which||(a.which=b.charCode?
b.charCode:b.keyCode);return a}},mouse:{props:"clientX clientY offsetX offsetY pageX pageY screenX screenY".split(" "),fix:function(a,b){var c,e,k=b.button,q=b.fromElement;null==a.pageX&&null!=b.clientX&&(c=a.target.ownerDocument||document,e=c.documentElement,c=c.body,a.pageX=b.clientX+(e&&e.scrollLeft||c&&c.scrollLeft||0)-(e&&e.clientLeft||c&&c.clientLeft||0),a.pageY=b.clientY+(e&&e.scrollTop||c&&c.scrollTop||0)-(e&&e.clientTop||c&&c.clientTop||0));!a.relatedTarget&&q&&(a.relatedTarget=q===a.target?
b.toElement:q);!a.which&&void 0!==k&&(a.which=k&1?1:k&2?3:k&4?2:0);return a}},touch:{props:["touches","targetTouches","changedTouches"],fix:function(a){return a}}},_props:"altKey bubbles cancelable ctrlKey currentTarget eventPhase shiftKey target timeStamp which".split(" "),_fix:function(a){var b={preventDefault:function(){a.preventDefault?a.preventDefault():a.returnValue=!1},stopPropagation:function(){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}},c=a.type,e=/^(key|mouse|touch)/.exec(c);
e&&-1!==["key","mouse","touch"].indexOf(e[1])&&(c=e[1]);"click"===c&&(c="mouse");for(var c=this._fixHooks[c]||{},e=c.props?this._props.concat(c.props):this._props,k=e.length;k;){var q=e[--k];b[q]=a[q]}b.target&&3===b.target.nodeType&&(b.target=b.target.parentNode);b.target||(b.target=a.srcElement||document);c.fix&&c.fix(b,a);b.originalEvent=a;b.type=a.type;b.timeStamp=a&&a.timeStamp||(new Date).valueOf();return b}};Splash.DOMEvent=a})();
(function(a,b){function c(a,c,h){this.content=a;this.tipSide=h||"bottom";this.listenTo=c;this.node=b.createElement("div");this.node.className="hint";-1!==navigator.userAgent.indexOf("MSIE 6")&&(this.nodeIE=b.createElement("iframe"),this.nodeIE.className="hint hint_iframe");this._prepareHTML();this._prepareEvents();this.enable()}c.prototype=new Splash.EventEmitter;mr.extend(c.prototype,{isVisible:function(){return this._visible},show:function(a){if(!(a&&!this._visible||!a&&this._visible)){this._inBody||
(this.nodeIE&&b.body.appendChild(this.nodeIE),b.body.appendChild(this.node),this._inBody=!0);a||this.emit("show");this.node.style.visibility="hidden";this.node.style.display="block";var a=mr.position(this.listenTo),c=this.node.offsetHeight,h=this.node.offsetWidth;this.node.style.left=a.left+this.listenTo.offsetWidth/2-22+"px";this.node.style.top=a.top-c-6+"px";this.nodeIE&&(this.nodeIE.style.width=h,this.nodeIE.style.height=c,this.nodeIE.style.left=this.node.style.left,this.nodeIE.style.top=this.node.style.top,
this.nodeIE.style.display=this.node.style.display,this.nodeIE.style.visibility="visible");this.node.style.visibility="visible";this._visible=!0}},hide:function(){this.node.style.display="none";this.nodeIE&&(this.nodeIE.style.display=this.node.style.display);this._visible=!1},_prepareHTML:function(){var a='<i class="hint__tip hint__tip_'+this.tipSide+'">'+(-1!==navigator.userAgent.indexOf("MSIE 6")?'<i class="hint__tip_ie"></i>':"")+'</i><div class="hint__content">'+this.content;this.node.innerHTML=
a;this.show(!0)},setContent:function(a){this.content=a;this._prepareHTML()},_prepareEvents:function(){var a;this._showEvent=new Splash.DOMEvent(this.listenTo,"mouseover",mr.proxy(function(){clearTimeout(a);a=setTimeout(mr.proxy(function(){this.show()},this),100)},this));var b=mr.proxy(function(){clearTimeout(a);a=setTimeout(mr.proxy(function(){this.hide()},this),400)},this);this._hideEvent=new Splash.DOMEvent(this.listenTo,"mouseout",b);mr.bind(this.node,"mouseover",function(){clearTimeout(a)});mr.bind(this.node,
"mouseout",b)},enable:function(){this._showEvent.attach();this._hideEvent.attach()},disable:function(){this._showEvent.detach();this._hideEvent.detach()},destroy:function(){this.node.parentNode.removeChild(this.node);this._showEvent.destroy();this._hideEvent.destroy();this._events.destroy();this._events=this._hideEvent=this._showEvent=this.content=this.tipSide=this.listenTo=this.node=null}});Splash.Hint=c})(window,document,void 0);
(function(){function a(a,c){this.container=a;this.options=c;this.mask=mr.id(c.mask.maskId);this.contentContainer=mr.id(c.content.containerId);this.more=mr.id(c.tabs.moreId);this.moreContainer=mr.id(c.tabs.moreDropdownId);var f=this;this.__onClick=function(a){f._onClick(this,a)};for(var d=this.container.getElementsByTagName("td"),h=0,e=d.length;h<e;h++)this._initTab(d[h]);this._closeMore=this._closeMore.bind(this);Splash.DOMEvent.addListener(this.more,"click",this._openMore.bind(this))}a.prototype=
new Splash.EventEmitter;mr.extend(a.prototype,{_initTab:function(a){this.isActive(a)&&(this.activeTab=a);this._loadTabContent(a);this._initDouble(a);Splash.DOMEvent.addListener(a,"click",this.__onClick)},loaded:function(){this._waiting&&this._waiting();this.emit("loaded")},_initDouble:function(a){mr.hasClass(a,this.options.tabs.doubleTabClass)&&(a._double=document.createElement("div"),a._double.className=this.options.tabs.moreDropdownItemClass,a._double.innerHTML=a.innerHTML.replace(RegExp(this.options.tabs.tabLinkClass,
"g"),this.options.tabs.moreDropdownItemLinkClass),a._double.tab=a,Splash.DOMEvent.addListener(a._double,"click",this.__onClick),this.moreContainer.appendChild(a._double))},_openMore:function(a){!mr.hasParent(a.target,this.moreContainer)&&!mr.hasClass(this.more,this.options.tabs.moreOpenedClass)&&(mr.counter("clb818633"),mr.addClass(this.more,this.options.tabs.moreOpenedClass),setTimeout(function(){Splash.DOMEvent.addListener(document,"click",this._closeMore)}.bind(this),0))},_closeMore:function(){mr.removeClass(this.more,
this.options.tabs.moreOpenedClass);Splash.DOMEvent.removeListener(document,"click",this._closeMore)},_loadTabContent:function(a){if(a._content)return!0;var c=document.getElementById("slot_"+a.getAttribute("data-slot"));if(c){var f;mr.hasClass(c.parentNode,this.options.content.tabClass)?f=c.parentNode:(f=document.createElement("div"),f.className=this.options.content.tabClass,f.style.display="none",c.style.display="",this.contentContainer.appendChild(f),f.appendChild(c));a._content=f;return!0}return!1},
_onClick:function(a,c){a.tab&&(a=a.tab);this.isActive(a)||(c.preventDefault(),this.activateTab(a))},isActive:function(a){return mr.hasClass(a,this.options.tabs.tabActiveClass)},activateTab:function(a){this.activeTab&&this.deactivateTab(this.activeTab);var c=a.getAttribute("data-counters");c&&mr.counter(c);mr.addClass(a,this.options.tabs.tabActiveClass);this._loadTabContent(a)?(a._content.style.display="block",this._waiting=null,this.mask.style.display="none"):(this.mask.style.display="block",this._waiting=
function(){this._loadTabContent(a);a._content.style.display="block";this.mask.style.display="none"});a._double?(mr.addClass(a._double,this.options.tabs.moreDropdownItemSelectedClass),mr.addClass(this.more,this.options.tabs.moreSelectedClass)):mr.removeClass(this.more,this.options.tabs.moreSelectedClass);this.activeTab=a;this.emit("tab:activate",a)},deactivateTab:function(a){mr.removeClass(a,this.options.tabs.tabActiveClass);this._loadTabContent(a)&&(a._content.style.display="none");a._double&&mr.removeClass(a._double,
this.options.tabs.moreDropdownItemSelectedClass);this.activeTab=null}});Splash.News=a})();
(function(a,b,c){function f(a){var b=a.relatedTarget,m=!1,c=a.type;a.type=ia[c];if(b!==this&&(b&&(m=j.contains(this,b)),!m))b=j.mkarr(arguments),l.fire(this,b.shift(),b),a.type=c}function d(g){function z(a,g){return l.add(aa,a,g)}function c(a,g){a&&l.rm(aa,a,g)}function i(a,g){a&&l.fire(aa,a,g)}function e(){return{current:P.curr,recent:P.rcnt,previous:P.prev,value:C,data:H,fullData:O,focused:D(L),method:ba,selected:D(Y),result:X(Y),itemData:I(Y),hovered:D(N),items:j.mkarr(Q)}}function f(){N=L=Y=ba=
O=H=C=null}function p(a){L=null;R(a.currentTarget)}function h(){}function k(){}function w(){}function q(a){a[ga]();a[Z]();a=D(a.currentTarget);-1!=a&&(ba="mouse",wa(a))}function s(){if(/^(?:relative|absolute|fixed)$/i.test(j.css(F,"position"))){var g=ja({},x.getBoundingClientRect());g.left+=a.pageXOffset+(n.shiftX||0);g.top+=a.pageYOffset+x.offsetHeight+(n.shiftY||0);j.css(F,"left",g.left+"px");j.css(F,"top",g.top+"px")}}function y(a){a=a?"on":"off";j.attr(x,"autocomplete",a);j.attr(x,"autocapitalize",
a);j.attr(x,"autocorrect",a);ca&&(E(ca),ca=null);j.hasFocus(x)&&(x.blur(),ca=S(function(){(!b.activeElement||!/^(?:a|input|textarea|select|button|)$/i.test(b.activeElement.tagName)||j.hasFocus(x))&&x.focus();ca&&(E(ca),ca=null)},25))}function B(){E(ka);ka=null}function v(){ka=S(function(){xa?v():(E(ka),ka=null,T())},50)}function A(){xa=!0}function G(){xa=!1;l.fire(x,"focus")}function u(){E(ra);ra=null}function J(a){var g=a.keyCode,b=a.shiftKey,z=a.ctrlKey;switch(!0){case !z&&!b&&(38==g||40==g)&&!U():a[Z]()}if(!ra)switch(ra=
S(u,n.keynavDelay),!0){case 13==g:if(!U()&&L&&(ba="keyboard",g=wa(L,!0),!n.autoSubmit||!1===g))a[Z]();break;case 27==g:U()||(T(),ya(),S(ya,15),a[Z]());break;case !z&&!b&&38==g:U()||$(-1);break;case !z&&!b&&39==g:!U()&&null!=O&&null!=H&&null!=C&&L&&X(L)!==C&&za(X(L));break;case !z&&!b&&40==g:U()?za():$(1)}}function V(){u()}function D(a){var g;"number"===typeof a?g=a:a&&a.nodeType&&(g=j.indexOf(Q,a));return"number"===typeof g&&!isNaN(g)?g:-1}function Aa(a){var g;if("number"===typeof a)g=Q[a];else if(a&&
a.nodeType&&~(a=j.indexOf(Q,a)))g=Q[a];return g||null}function I(a){a=D(a);return H&&null!=H[a]?H[a]:null}function R(a){var g=Aa(a),b=n.hover;!N&&!g||N===g||(b&&("string"===typeof b?(N&&j.rmCls(N,b),g&&j.addCls(g,b)):M(b)&&(N&&(a=D(N),b(!1,N,I(a),a,C)),g&&(a=D(g),b(!0,g,I(a),a,C)))),N=g)}function W(a){var a=D(a),g=Aa(a),b=I(a);R(a);i(r.focus,[b,a,C]);L=g;if(n.preview){var g=D(a),z=I(g),g=null!=z?n.result(z,g,O,C):C;P.setIgnore(g)}i(r.focusEnd,[b,a,C])}function $(a){var g=L||N,b=g?D(g):-1,g=Q.length-
1,a=b+a;-1>a?a=g:a>g&&(a=-1);W(a)}function X(a){var a=D(a),g=I(a);return null!=g?n.result(g,a,O,C):null}function ya(){P.setIgnore(C);x.value=C}function wa(g,z){g=D(g);Y=-1==g?null:Aa(g);W(g);I(g);var c=n.select,m,f=!1;i(r.select,e());T();ya();M(c)&&(m=c(e()));var d;if(d=!1!==m)d=D(g),(d=X(d))&&P.setIgnore(d),d=da&&n.autoSubmit;if(d)if(z)f=!0;else{var p=!1;b.createEvent?(Ba(da,"submit",function(g){g=g||a.event;p=Fa(g);ea.preventDefault.call({origEvt:g})}),c=b.createEvent("HTMLEvents"),c.initEvent("submit",
!1,!0),da.dispatchEvent(c)):b.createEventObject&&(c=b.createEventObject(),p=!da.fireEvent("onsubmit",c));!1===p&&da.submit()}f?b[sa]?Ba(da,"submit",Ca):Ba(da,"submit",function(){S(Ca,50)}):Ca();return m}function Ca(){var a=n.unselect;M(a)&&a(e());i(r.selectEnd,e());Y=ba=null}function za(a){null!=O&&null!=H&&null!=C&&(!a||a===C)?(Da(),L&&W(L)):a?P.fireVal(a,!0):P.fire(!0)}function U(){var a=!0,g=n.switcher,b=n.switchChecker;g?"string"===typeof g?a=!j.hasCls(F,n.switcher):M(g)&&M(b)&&(a=!b()):a="none"===
j.css(F,"display");return a}function Da(){if(U()){i(r.open,[C]);var a=n.switcher;a?"string"===typeof a?j.addCls(F,a):M(a)&&a(!0,F):j.css(F,"display","block");n.correction&&s();i(r.openEnd,[C])}}function T(){if(!U()){i(r.close,[C]);var a=n.switcher;a?"string"===typeof a?j.rmCls(F,a):M(a)&&a(!1,F):j.css(F,"display","none");i(r.closeEnd,[C])}}function ia(a){a.target!==x&&T()}function Ea(){s()}function oa(){la&&(i(r.enable),l.add(b,"click",ia),l.add(F,"click",fa),l.add(x,"focus",B),l.add(x,"blur",v),
l.add(F,"mousedown",A),l.add(F,"mouseup",G),l.add(x,K?"keypress":"keydown",J),l.add(x,"keyup",V),n.correction&&l.add(a,"resize",Ea),y(!1),P.init(),la=!1,i(r.enableEnd))}function pa(){la||(i(r.disable),T(),P.off(),Ga.abortAll(),y(!0),l.rm(b,"click",ia),l.rm(F,"click",fa),l.rm(x,"focus",B),l.rm(x,"blur",v),l.rm(F,"mousedown",A),l.rm(F,"mouseup",G),l.rm(x,K?"keypress":"keydown",J),l.rm(x,"keyup",V),n.correction&&Ea&&l.rm(a,"resize",Ea),j.empty(ta),Q.length=0,N=L=Y=ba=null,la=!0,i(r.disableEnd))}function va(a){try{console.log(a.type,
arguments)}catch(g){}}function qa(a,g){var b=arguments.length;if(0==b)return n;if(1==b&&"object"!==typeof a)return j.walker(n,a);"object"!==typeof a&&(b={},b[a]=g,a=b);var i;i=a;if(null==i)i=null;else{var e={};(function Ha(a,g){a&&(j.isObj(a)?j.objEach(a,function(a,b){Ha(a,(g?g+".":"")+b)}):g&&(e[g]=a))})(i);i=e}(b=i)&&j.objEach(b,function(a,g){var b=j.walker(n,g,a);if(/(?:^on[A-Z])/.test(g.substr(0,3))&&M(a)){var i=g.charAt(2).toLowerCase()+g.slice(3);if(i=d.evt[i])b&&c(i,b),z(i,a)}})}var aa=this,
P={run:!1,did:null,prev:null,rcnt:null,curr:null,ignr:null,init:function(){this.run||(this.curr=this.prev=x.value,this.on())},handler:function(a){var g=this.curr=x.value,b=this.prev;if(a||g!==b){!a&&null==this.ignr&&(this.rcnt=b);this.prev=g;if(a||null==this.ignr||this.ignr!==g){i(r.valueChange,[g,b,this.rcnt]);var a=""+g,b=a.length,z=!0;if(n.valMin&&b<n.valMin||n.valMax&&b>n.valMax)z=!1;b=n.valFilter;z&&b&&(z=b instanceof RegExp?b.test(a):M(b)?b(a):b===a);z?(i(r.passFilter,[g]),Ga.send(g,function(a,
g){if(g===x.value){var b=n.dataGet;C=g;H=(O=a)&&M(b)?b(O):O;b=!1;if(!O||!H||!H.length||n.min&&n.min>H.length)b=!0;if(b)i(r.rejectData,[a,g]),f(),T();else{i(r.acceptData,[a,g]);j.empty(ta);Q.length=0;N=L=Y=ba=null;i(r.render,[H,C]);for(var b=n.max?Math.min(H.length,n.max):H.length,z=0,c,m=M(n.item)?n.item:j.tmpl(n.item);z<b;z++){c=H[z];(c=m({itemData:c,fullData:O,index:z,value:C}))&&"string"===typeof c&&(c=j.cre(c));if(!c||!c.nodeType)break;l.add(c,"click",q);l.add(c,"mouseenter",p);l.add(c,"mouseleave",
h);l.add(c,"mousedown",k);l.add(c,"mouseup",w);Q.push(c);ta.appendChild(c)}i(r.renderEnd,[Q,H,C]);Da()}}},function(a,g){g===x.value&&(f(),T())})):(i(r.failFilter,[g]),f(),T())}this.ignr=null}},fire:function(a){this.off();this.handler(a);this.on()},fireVal:function(a,g){this.off();x.value=a;this.handler(g);this.on()},on:function(){if(!this.run){var a=this;this.run=!0;this.did=Ia(function(){a.handler()},n.delay)}},off:function(){this.run&&(this.run=!1,Ja(this.did),this.did=null)},setIgnore:function(a){x.value!==
a&&(this.ignr=x.value=a)}},ma={c:{},i:0,set:function(a,g){i(r.setCache,[a,g]);n.cchLimit&&this.i+1>=n.cchLimit&&this.flush();this.c[a]=g;this.i++;i(r.setCacheEnd,[a,g,this.i])},get:function(a){i(r.getCache,[a]);var g=this.has(a)?this.c[a]:null;i(r.getCacheEnd,[a,g]);return g},has:function(a){return null!=this.c[a]&&t.call(this.c,a)},flush:function(){i(r.flushCache);var a=this.c,g;for(g in a)t.call(a,g)&&delete a[g];this.i=0;i(r.flushCacheEnd)}},Ga={act:[],actVals:{},isAct:function(a){return!arguments.length?
!!this.act.length:!!this.actVals[a]&&t.call(this.actVals,a)},add:function(a,g){var b=this.act;n.reqMax&&b.length&&b.length>=n.reqMax&&this.rm(b[0]);this.actVals[g]=a;return b.push(a)},rm:function(a){if(a){a.abort();var g=j.indexOf(this.act,a);~g&&this.act.splice(g,1);var b=this.actVals;for(g in b)if(b[g]===a){delete b[g];break}return this.act.length}},abortAll:function(){for(var a=this.act,g=this.actVals,b=a.length;b--;)a[b]&&a[b].abort();a.length=0;for(b in g)delete g[b]},stack:function(){return j.mkarr(this.act)},
send:function(a,g,b){if(!a)return!1;var z=this;if(n.cch&&ma.has(a))return g&&g(ma.get(a),a),!0;if(this.isAct(a))return i(r.blockRequest,["running",a]),!1;var c=n.url,m={query:a},c="object"===typeof c?j.url(j.objFormat(c,m)):j.format(c,na(m)),e=Ka({timeout:n.reqTimeout,callbackParam:n.callbackParam,scriptCharset:n.scriptCharset,data:n.reqData,success:function(b){i(r.successRequest,[b,a]);i(r.completeRequest,[b,a]);var c=n.dataFilter;M(c)&&(b=c(b,a));z.rm(e)||i(r.stopRequest,[a]);n.cch&&ma.set(a,b);
g&&g(b,a)},error:function(g){i(r.errorRequest,[g,a]);i(r.completeRequest,[g,a]);z.rm(e)||i(r.stopRequest,[a]);b&&b(g,a)}});1==z.add(e,a)&&i(r.startRequest,[a]);i(r.sendRequest,[a]);e.send(c);return!0}},O=null,H=null,C=null,ca,ka,ra,n=j.copy(d.opts);qa(g);var x=n.field&&ua(n.field),da=x&&x.form,F=ua(n.cont),ta=n.list&&F?ua(n.list,F):F,Q=[],N,L,Y,xa,la=!0,ba=null;if(!x||!F||!ta)throw"";n.debug&&j.objEach(r,function(a){z(a,va)});ja(this,{show:za,focus:W,moveFocus:$,select:wa,open:Da,close:T,isClosed:U,
enable:oa,disable:pa,isDisabled:function(){return la},destroy:function(){i(r.destroy);pa();n.cch&&ma.flush();c();i(r.destroyEnd);delete d.instances[aa.guid]},on:z,off:c,getState:e,opts:qa,flushCache:function(){ma.flush()}});aa.guid=ha++;d.instances[aa.guid]=aa;n.enabled&&oa()}var h,e=b,k=function(a){var b,m;if(a&&(m=a.length)!==c)try{b=Array.prototype.slice.call(a)}catch(i){for(b=Array(m);m--;)b[m]=a[m]}return b||[]},q=function(a,b){var m=[],b=b?q(b)[0]:e;if(!a)return m;if(a.nodeType||"object"===
typeof a&&"setTimeout"in a)return[a];if("object"===typeof a&&("[object Array]"===Object.prototype.toString.call(a)||a.length!==c))return k(a);if(!b)return m;if(/^[\w#.][\w\]*^|=!]*$/.test(a)){var i=0;switch(a.charAt(0)){case "#":i=a.slice(1);(m=e.getElementById(i))&&m.id!==i&&(m=e.all[i]);m=m?[m]:[];break;case ".":var d=a.slice(1);if(p)m=(m=b.getElementsByClassName(d)).length?m:[];else{for(var d=" "+d+" ",f=b.getElementsByTagName("*"),j=0,h;h=f[j++];)-1!=(" "+h.className+" ").indexOf(d)&&(m[i++]=
h);m=i?m:[]}break;default:m=(m=b.getElementsByTagName(a)).length?m:[]}}else{j=~a.indexOf("!=");if(w&&!j)try{m=b.querySelectorAll(a.replace(/=([^\]]+)/,'="$1"'))}catch(l){f=!0}if(f||!w||j){h=a.split(/ *, */);for(var S=h.length-1,s=!!S,K,t,y,r,B,v,A,G,u,D,E;f=h[S--];){t=(K=f.replace(/(\([^)]*)\+/,"$1%").replace(/(\[[^\]]+)~/,"$1&").replace(/(~|>|\+)/," $1 ").split(/ +/)).length;j=0;y=" ";for(f=[b];i=K[j++];)if(" "!==i&&">"!==i&&"~"!==i&&"+"!==i&&f){i=i.match(/([^[:.#]+)?(?:#([^[:.#]+))?(?:\.([^[:.]+))?(?:\[([^!&^*|$[:=]+)([!$^*|&]?=)?([^:\]]+)?\])?(?:\:([^(]+)(?:\(([^)]+)\))?)?/);
r=i[1]||"*";B=i[2];d=i[3]?" "+i[3]+" ":"";v=[];i=A=0;for(u=j==t;G=f[A++];)switch(y){case " ":G=G.getElementsByTagName(r);for(E=0;D=G[E++];)if((!B||D.id===B)&&(!d||-1!=(" "+D.className+" ").indexOf(d))&&!D.yeasss)u&&(D.yeasss=1),v[i++]=D}f=v}else y=i;if(s){if(!f.concat){v=[];for(E=0;D=f[E];)v[E++]=D;f=v}m=f.concat(1==m.length?m[0]:m)}else m=f}for(i=m.length;i--;)m[i].yeasss=m[i].nodeIndex=m[i].nodeIndexLast=null}}return k(m)},p=!!e.getElementsByClassName,w=!!e.querySelectorAll;h=q;var K=/opera/i.test(navigator.userAgent)&&
!!a.opera,s=Object.prototype,t=s.hasOwnProperty,B=s.toString,y=Array.prototype.slice,G=Array.prototype.forEach,u=Array.prototype.indexOf,A=Array.prototype.map,V=String.prototype.trim,na=encodeURIComponent,S=a.setTimeout,Ia=a.setInterval,E=a.clearTimeout,Ja=a.clearInterval,J=Date.now||function(){return+new Date},I=/\s+/,La=/\{(\w*)\}/mg,Ma=/([-\\()^$.?+*])/g,v="SG"+J(),ha=1,fa=function(){return!1},W=function(){return!0},s=function(){},j={isArr:Array.isArray||function(a){return"[object Array]"===B.call(a)},
isFn:function(a){return"[object Function]"===B.call(a)},isObj:function(a){if(!a||"object"!==typeof a||j.isArr(a)||j.isFn(a)||a.nodeType||a.setTimeout||a.constructor&&!t.call(a,"constructor")&&!t.call(a.constructor.prototype,"isPrototypeOf"))return!1;for(var b in a);return b===c||t.call(a,b)},isWin:function(a){return!!a&&"object"===typeof a&&"setInterval"in a},ext:function(){var a,b,m,i,e,f=arguments,d=f[0]||{},p=1,h=f.length,k=!1;"boolean"===typeof d&&(k=d,d=f[1]||{},p=2);for("object"!==typeof d&&
!j.isFn(d)&&(d={});p<h;p++)if(null!=(a=f[p]))for(b in a)m=d[b],i=a[b],d!==i&&(k&&i&&(j.isObj(i)||(e=j.isArr(i)))?(e?(e=!1,m=m&&j.isArr(m)?m:[]):m=m&&j.isObj(m)?m:{},d[b]=ja(k,m,i)):i!==c&&(d[b]=i));return d},copy:function(a){return j.ext(!0,j.isArr(a)?[]:{},a)},trim:function(a){a=""+a;return V?V.call(a):a.replace(/^\s+|\s+$/,"")},arrEach:function(a,b,c){if(G)G.call(a,b,c);else for(var i=0,d=a.length;i<d;i++)b.call(c,a[i],i)},objEach:function(a,b,c){for(var i in a)t.call(a,i)&&b.call(c,a[i],i)},each:function(a,
b,c){j["number"===typeof a.length?"arrEach":"objEach"](a,b,c)},map:function(a,b,c){if(A)return A.call(a,b,c);for(var i=0,d=a.length,e=Array(d);i<d;i++)e[i]=b.call(c,a[i],i);return e},indexOf:function(a,b,c){if(u)return u.call(a,b,c);var c=c||0,i=-1,d=0,e=a.length;if(c<e)for(0>c&&(d=Math.max(e-Math.abs(c),0));d<e;d++)if(a[d]===b){i=d;break}return i},format:function(a,b){return a&&b?(""+a).replace(La,function(a,g){return t.call(b,g)?b[g]:""}):""},objFormat:function(a,b){var c={};j.objEach(a,function(a,
g){c[g]="string"===typeof a?j.format(a,b):j.isObj(a)?j.objFormat(a,b):a});return c},walker:function(a,b,c){for(var i=2<arguments.length,d=b.split("."),e=0,f=d.length,p=a,h,k=null,w,l;e<f;e++)if(h=d[e],k=(p=k||p)[h],l=e==f-1,null==k||!l&&!j.isObj(k))if(i)l||(k=p[h]={});else{k=null;break}e==f&&i?(w=p[h],p[h]=c):c=k;return i?w:c},resc:function(a){return(""+a).replace(Ma,"\\$1")},from:function(a){return null==a?[]:j.isArr(a)?a:[a]},mkarr:function(a){var b,d;if(a&&(d=a.length)!==c)try{b=y.call(a)}catch(i){for(b=
Array(d);d--;)b[d]=a[d]}return b||[]},prm:function(a){var b,c,d=[];for(b in a)t.call(a,b)&&d.push(j.map([b,j.isFn(c=a[b])?c():c],na).join("="));return d.join("&")},aprm:function(a,b){if(!b)return a;var a=""+a,c=[a],d=a.charAt(a.length-1);c.push(!~a.indexOf("?")?"?":"?"!==d&&"&"!==d?"&":"");c.push("object"===typeof b?j.prm(b):b);return c.join("")},url:function(a){var b=[];a.scheme&&b.push(a.scheme,":");a.authority&&b.push("//",a.authority);a.path&&b.push("/",!a.path.indexOf("/")?a.path.slice(1):a.path);
a.query&&b.push(j.aprm("?",a.query));a.fragment&&(a=a.fragment,b.push("#","object"===typeof a?j.prm(a):a));return b.join("")},$:function(a,b){return h(a,b)[0]||null},$$:h,css:function(a,b,c){if(!a)return null;var d=null;if(2<arguments.length&&b)a.style[b]=c;else{var e=a.ownerDocument.defaultView.getComputedStyle(a,null);1==arguments.length?d=j.mkarr(e):b&&(d=e.getPropertyValue(b))}return d},addCls:function(a,b){for(var c=j.trim(b).split(I),d=c.length,e=a.className;d--;)b=c[d],j.hasCls(a,b)||(e+=" "+
b);a.className=j.trim(e)},rmCls:function(a,b){if(1<arguments.length){for(var c=j.trim(b).split(I),d=c.length,e=a.className;d--;)b=c[d],e=e.replace(RegExp("(?:^|\\s+)"+j.resc(b)+"(?:\\s+|$)","g")," ");a.className=j.trim(e)}else a.className=""},hasCls:function(a,b){b=j.trim(b);return!(!a||!a.nodeType||!b||!~(" "+a.className+" ").indexOf(" "+b+" "))},cres:function(a){var a=j.trim(a),c=b.createDocumentFragment().appendChild(b.createElement("div"));c.innerHTML=a;return j.mkarr(c.childNodes)},cre:function(a){a=
j.trim(a);return"<"===a.charAt(0)&&">"===a.charAt(a.length-1)?j.cres(a)[0]:b.createElement(a)},rme:function(a){a&&a.parentNode&&(l.rm(a),a.parentNode.removeChild(a))},empty:function(a){for(var b;a&&(b=a.firstChild);)j.rme(b)},attr:function(a,b,c){2<arguments.length&&a.setAttribute(b,c);return a.getAttribute(b)},hasFocus:function(a){return!!a&&a.ownerDocument.activeElement===a},contains:b.documentElement.contains?function(a,b){return a!==b&&(a.contains?a.contains(b):!0)}:b.documentElement.compareDocumentPosition?
function(a,b){return!!(a.compareDocumentPosition(b)&16)}:fa},Na=j,X=function(a,b){var c,d="string"===typeof a,e=!1,f;d?(a=j.trim(a),e=(!a.indexOf("#")||!a.indexOf("."))&&0>a.indexOf(oa)+a.indexOf($)):a&&(f=!!a.nodeType);if(e||f){if(f&&a[v]?c=R[a[v]]:f||(c=R[a]),!c&&(e=h(a)[0]))c=R[e[v]||(e[v]=ha++)]=X(e.innerHTML||""),d&&(R[a]=c)}else c=a,c=R[c]||(R[c]=Function("_o","_e","var _=[],print=function(){_.push.apply(p,arguments)};with(_o||{}){_.push('"+c.replace(Oa," ").split(oa).join("\t").replace(Pa,
"$1\r").replace(Qa,function(a,b){b=j.trim(b);return!b?"":["');","try{_.push("+b+")}catch(e){_e.push(e)}","_.push('"].join("")}).split("\t").join("');").split($).join("_.push('").split("\r").join("\\'")+"')}return _.join('')"));c||(c=b?function(){return""}:"");return b?c(b,pa):c},oa="<%",$="%>",Oa=/[\r\t\n]/g,Pa=RegExp("((^|"+j.resc($)+")[^\\t]*)'","g"),Qa=RegExp("\\t=(.*?)"+j.resc($),"g"),pa=[],R={};X.errs=pa;X.cch=R;Na.tmpl=X;var ja=j.ext,M=j.isFn,ua=j.$,sa="addEventListener",Z="preventDefault",
ga="stopPropagation",Ra="altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),va=b[sa]?function(a,b,c){a[sa](b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:s,qa=b[sa]?function(a,b,c){a.removeEventListener(b,
c,!1)}:b.attachEvent?function(a,b,c){a.detachEvent("on"+b,c)}:s,Ba=function(a,b,c){va(a,b,function(){qa(a,b,arguments.callee);return c.apply(a,arguments)})},Fa=function(a){return"defaultPrevented"in a?a.defaultPrevented:"returnValue"in a?!a.returnValue:"getPreventDefault"in a?a.getPreventDefault():!1},l=j.Event={fired:null,c:{},custom:{},hlink:function(a,b){b[v]=a[v]=a[v]||ha++;return b},fix:function(a){if(a[v])return a;for(var d=a,a=new l.Event(a),e=0,f;f=Ra[e++];)a[f]=d[f];a.target||(a.target=a.srcElement||
b);3===a.target.nodeType&&(a.target=a.target.parentNode);!a.relatedTarget&&a.fromElement&&(a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement);null==a.pageX&&null!=a.clientX&&(e=a.target.ownerDocument||b,d=e.documentElement,e=e.body,a.pageX=a.clientX+(d&&d.scrollLeft||e&&e.scrollLeft||0)-(d&&d.clientLeft||e&&e.clientLeft||0),a.pageY=a.clientY+(d&&d.scrollTop||e&&e.scrollTop||0)-(d&&d.clientTop||e&&e.clientTop||0));if(null==a.which&&(null!=a.charCode||null!=a.keyCode))a.which=null!=
a.charCode?a.charCode:a.keyCode;!a.metaKey&&a.ctrlKey&&(a.metaKey=a.ctrlKey);!a.which&&a.button!==c&&(a.which=a.button&1?1:a.button&2?3:a.button&4?2:0);return a},handler:function(b,c){b=l.fix(b||a.event);b.currentTarget=this;var d=l.c[this[v]][b.type],e;(c=c&&j.isArr(c)?j.mkarr(c):null)&&c.unshift(b);for(var f=0,p=d.length;f<p&&!(e=d[f],e=c?e.apply(this,c):e.call(this,b),!1===e&&(b[Z](),b[ga]()),b.isImmediatePropagationStopped());f++);},add:function(b,c,d){b&&c&&M(d)&&(b.setInterval&&b!=a&&!b.frameElement&&
(b=a),j.arrEach(c.split(I),function(a){d[v]||(d[v]=ha++);var c=b[v]=b[v]||ha++,c=l.c[c]=l.c[c]||{},c=c[a]=c[a]||[],e=c.handle=function(a,b){if(!a||a.type!==l.fired)return l.handler.call(e.elem,a,b)};e.elem=b;if(1==c.push(d)&&(b.nodeType||b.setInterval)){var f=l.custom&&l.custom[a]&&l.custom[a].setup;(!f||!1===f.call(b,e))&&va(b,a,c.handle)}}))},one:function(a,b,c){l.add(a,b,l.hlink(c,function(){l.rm(this,b,arguments.callee);return c.apply(this,arguments)}))},rm:function(b,c,d){if(b)if(c)b.setInterval&&
b!=a&&!b.frameElement&&(b=a),j.arrEach(c.split(I),function(a){var c=b[v],e=c&&l.c[c],f=e&&e[a];if(c&&e&&f){if(M(d)&&d[v])for(var i=f.length;i--;){if(f[i][v]==d[v]){f.splice(i,1);break}}else f.length=0;if(!f.length){if(b.nodeType||b.setInterval)i=l.custom&&l.custom[a]&&l.custom[a].teardown,(!i||!1===i.call(b,f.handle))&&qa(b,a,f.handle);delete e[a];for(a in e)return;delete l.c[c]}}});else{var c=(c=b[v])&&l.c[c],e=[],f;if(c){for(f in c)t.call(c,f)&&e.push(f);l.rm(b,e.join(" "))}}},fire:function(a,b,
c){var d;if(a&&b){var c=j.from(c),e=b.type||b,f,p="on"+e,h=a[v];if(d=(h=h&&l.c[h])&&h[e],h=d)f=b[v]?b:"object"===typeof b?new l.Event(e,b):new l.Event(b),f.type=e,f.target=f.currentTarget=a,h.handle.call(a,f,c);if(!f||!f.isDefaultPrevented()){var k;try{if((a.nodeType||a.setInterval)&&p&&a[e])(k=a[p])&&(a[p]=null),l.fired=e,a[e]()}catch(w){}k&&(a[p]=k)}l.fired=null}}};l.Event=function(a,b){a&&a.type?(this.origEvt=a,this.type=a.type,this.isDefaultPrevented=Fa(a)?W:fa):this.type=a;b&&ja(this,b);this.timeStamp=
J();this[v]=!0};var ea=l.Event.prototype;ea[Z]=function(){this.isDefaultPrevented=W;var a=this.origEvt;if(a)if(a[Z])a[Z]();else a.returnValue=!1};ea[ga]=function(){this.isPropagationStopped=W;var a=this.origEvt;if(a){if(a[ga])a[ga]();a.cancelBubble=!0}};ea.stopImmediatePropagation=function(){this.isImmediatePropagationStopped=W;this[ga]()};ea.isDefaultPrevented=fa;ea.isPropagationStopped=fa;ea.isImmediatePropagationStopped=fa;var ia={mouseover:"mouseenter",mouseout:"mouseleave"};j.objEach(ia,function(a,
b){l.custom[a]={setup:function(){l.add(this,b,f)},teardown:function(){l.rm(this,b,f)}}});var Sa="cb"+v,Ka=j.jsonp=function(c){function e(){try{delete a[p]}catch(b){}}function d(a){l=k=!0;h&&h.onload();s&&s(a)}var f,p,h,k,w,l,q=c.success,s=c.error;return{send:function(s){l=!1;f=b.head||ua("head,body")||b.documentElement;p=Sa+ha++;h=j.cre("script");c.scriptCharset&&(h.charset=c.scriptCharset);h.async=!0;h.onload=h.onreadystatechange=function(){if(k||!this.readyState||"loaded"===this.readyState)h.onload=
h.onreadystatechange=null,h&&h.parentNode&&f.removeChild(h),h=null,E(w),l=!0,k&&(a[p]=e)};var K=ja({},c.data);K[c.callbackParam]=p;s=j.aprm(s,K);h.src=s;a[p]=function(a){l=!0;e();q&&q(a)};c.timeout&&(w=S(function(){d("timeout")},c.timeout));f.insertBefore(h,f.firstChild);return this},abort:function(){l||d("user");return this}}},r=d.evt={};j.arrEach("open openEnd close closeEnd enable enableEnd disable disableEnd destroy destroyEnd blockRequest successRequest completeRequest stopRequest errorRequest startRequest sendRequest passFilter failFilter rejectData acceptData render renderEnd focus focusEnd select selectEnd valueChange flushCache flushCacheEnd setCache setCacheEnd getCache getCacheEnd".split(" "),
function(a){this[a]=a},r);d.instances={};d.opts={enabled:!0,field:"#q",cont:"#sg",switcher:"sg-open",delay:250,valMin:1,valMax:255,valFilter:/(?:\S)/,url:"//suggests.go.mail.ru/sg_mobi?q={query}",callbackParam:"callback",reqTimeout:5E3,reqMax:2,scriptCharset:"windows-1251",dataFilter:function(a){return a},dataGet:function(a){return a&&a.items?a.items:[]},cch:!0,cchLimit:128,max:5,min:0,autoSubmit:!0,hover:"sg-item-hover",item:'<div class="sg-item"><%= itemData.textMarked || itemData.text %></div>',
result:function(a){return a.text},select:function(){},keynavDelay:150,preview:!0,debug:!1};d.utils=j;a.SG=a.SG||d})(window,document);(function(){var a=new Image;window.dataURISupported=!1;a.onload=a.onerror=function(a){a||(a=window.event);window.dataURISupported="load"===a.type};a.src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="})();
(function(){var a=mr.id("q"),b=a.form,c=mr.id("go-form__sugg"),f=mr.id("go-form__sugg__items"),d=mr.id("go-form__sugg__loading"),h=mr.id("go-suggests__suggest-tmpl"),e=0,f=new SG({enabled:!1,field:a,cont:c,list:f,switcher:"go-form__sugg_open",autoSubmit:!0,preview:!0,hover:"go-form__sugg__item_select",max:7,scriptCharset:"utf-8",url:{scheme:0==location.href.indexOf("https://")?"https":"http",authority:"suggests.go.mail.ru",path:"sg_u",query:{q:"{query}"}},reqTimeout:3E3,reqData:{},dataFilter:function(a){if(a&&
a.items){var b=a.items,c,e,d=a.sites&&a.sites.length||0,f=[];for(e=0;e<d;e++)c=a.sites[e],"site"===c.type&&f.push(c);for(e=b.length;e--;)c=b[e],"site"===c.type&&b.splice(e,1);f.length&&b.unshift.apply(b,f)}return a},item:h,result:function(a){return a.text},onRenderEnd:function(){if(window.__ie7||window.__ie6)c.style.display="none",c.style.display="block"},onStartRequest:function(){d.style.display="block"},onStopRequest:function(){d.style.display="none"}}),k;f.opts({select:function(a){var c=a.itemData,
d=a.value;if("site"===c.type)k=a;else{a={us:d.length};if(c.mus){a.usmus=1;a.rch="l";for(var f=b.getElementsByTagName("input"),h=0,q=f.length;h<q;h++)d=f[h],"rch"==d.name&&d.parentNode.removeChild(d)}c.spcAuto&&(a.ussp=c.spcAuto);var y=document.createDocumentFragment(),G=[],u;for(u in a)a.hasOwnProperty(u)&&(c=a[u],d=document.createElement("input"),d.type="hidden",d.name=u,d.value=c,G.push(d),y.appendChild(d));b.appendChild(y);setTimeout(function(){for(var a=0,b=G.length;a<b;a++){var c=G[a];c.parentNode.removeChild(c)}G=
y=null},10);e=1}},unselect:function(){k=null}});var q=[null,"615232","615227","615230"],h=mr.id("search__button__wrapper__field");Splash.DOMEvent.addListener(h,"mousedown",function(){e=2});b._action=b.action;Splash.DOMEvent.addListener(b,"submit",function(c){if(b._submited)return!0;if(/^\s*$/.test(a.value))return a.focus(),!1;1!=e&&2!=e&&(e=3);var d=q[e]?"//r.mail.ru/clb"+q[e]+"/"+b._action.replace(/(https?:)?(\/\/)?(.+)/i,"$3"):b._action;if(k){var f=k.itemData,h=k.value,t=document.createElement("form");
t.action=d;t.method="get";t.target="_blank";var f={q:f.link,sg:h,ce:1,sgsig:f.sig},B;for(B in f)if(f.hasOwnProperty(B)){var h=f[B],y=document.createElement("input");y.type="hidden";y.name=B;y.value=h;t.appendChild(y)}document.body.appendChild(t);t.submit();setTimeout(function(){t.parentNode.removeChild(t)},15);c.preventDefault()}e=0;b.action=d;b._submited=!0;clearTimeout(void 0);setTimeout(function(){b._submited=!1;b.action=b._action},200)});if(window.__ie6||window.__ie7)f.on("closeEnd",function(){c.style.display=
"none";c.style.display="block"});f.enable()})();
(function(){var a=mr.id("search__projects-list");mr.bind(a,"click",function(a){var a=a||window.event,c=a.target||a.srcElement;if("A"===c.tagName){var f=mr.id("q").value;if(f){var d=mr.data(c,"search-href");if(d){if(c=mr.data(c,"search-param")){var h=document.createElement("form");h.action=d;h.method="get";h.setAttribute("accept-charset","windows-1251");d=document.createElement("input");d.type="hidden";d.name=c;d.value=f;h.appendChild(d);document.body.appendChild(h);h.submit()}else location.href=d+
encodeURIComponent(f);mr.preventDefault(a)}}}})})();
(function(){var a=mr.id("Auth"),b=mr.id("js-mailbox-emails"),c=mr.id("js-unread"),f=mr.tag("*",c,"js-txt")[0],d=mr.id("js-readed"),h=mr.id("js-mailbox-user"),e=mr.id("js-mailbox-avatar"),k=mr.id("js-mailbox-writemail"),q=mr.id("js-mailbox-exit"),p=mr.id("mailbox__login"),w=mr.id("mailbox__login__domain"),K=mr.id("domain-widget"),s=mr.id("mailbox__password"),t=mr.id("mailbox__auth__remember__checkbox"),B=mr.id("js-mailbox-enter"),y={},G=new Splash.EventEmitter;mr.data(a,"loadsubmit-counter","d703061");
window.Splash.ajaxUpdates.push({data:"mailbox",cb:function(a){y&&a.hasAuth!==y.hasAuth&&G.emit("switch",{data:a,oldData:y});B.href=a.HasAuth?mr.data(B,"enter-href"):mr.data(B,"login-href");if(a.HasAuth)h.innerHTML=a.ActiveEmail,mr.isMultiAuth&&(mr.multiuser.innerHTML=a.ActiveEmail),mr.isFilin&&a.ActiveEmail!==y.ActiveEmail?e.style.backgroundImage="url(//filin.mail.ru/pic?from=splash&email="+a.ActiveEmail+(mr.retina?"&width=90&height=90":"&width=45&height=45")+")":a.PhotoBox!==y.PhotoBox&&(e.style.backgroundImage=
"url(//avt.foto.mail.ru/"+a.PhotoBox+"/_avatar"+(mr.retina?"":"small")+")"),e.name=a.TotalUnread?mr.data(e,"counter-unread"):mr.data(e,"counter-readed"),b.name=a.TotalUnread?mr.data(b,"counter-unread"):mr.data(b,"counter-readed"),k.name=a.TotalUnread?mr.data(k,"counter-unread"):mr.data(k,"counter-readed"),q.name=a.TotalUnread?mr.data(q,"counter-unread"):mr.data(q,"counter-readed"),a.TotalUnread?(f.innerHTML=a.TotalUnread+" "+_plural(a.TotalUnread,Splash.data.mailbox.newL)+" "+_plural(a.TotalUnread,
Splash.data.mailbox.letters),c.style.display="inline",d.style.display="none"):(d.style.display="inline",c.style.display="none"),mr.removeClass(document.body,"status__user_hasNoAuth"),mr.addClass(document.body,"status__user_hasAuth");else{if(document.activeElement&&-1!==document.activeElement.className.indexOf("mailbox"))return;var u=null,E=null;a.User&&(u=a.User+"@"+a.UserDomain);p.value&&(E=1!=mr.mailboxAuthType?p.value+w.options[-1==w.selectedIndex?1:w.selectedIndex].text:p.value);u!=E&&(s.value=
"");p.value=1!=mr.mailboxAuthType?a.User||"":a.User?a.User+"@"+a.UserDomain:"";mailboxLoginPlaceholder.toggle();for(mailboxPasswordPlaceholder.toggle();w&&w.firstChild;)w.removeChild(w.firstChild);if(a.Domains[0].Domain){mr.domains=[];for(var u=a.Domains.length,E=null,A=0;A<u;A++)E=a.Domains[A].Domain,mr.domains.push(E)}else mr.domains=a.Domains,mr.extDomains=a.ExtDomains;u=0;for(E=mr.domains.length;u<E;u++)if(A=mr.domains[u],w){var J=document.createElement("option");J.value=A;J.selected=a.UserDomain==
A;J.innerHTML="@"+A;w.appendChild(J)}if(mr.externalDomainsEnabled){var I=document.createElement("optgroup");I.label="\u2013\u2013\u2013\u2013";u=0;for(E=mr.extDomains.length;u<E;u++)A=mr.extDomains[u],w&&(J=document.createElement("option"),J.value=A,J.selected=a.UserDomain==A,J.innerHTML="@"+A,I.appendChild(J));w.appendChild(I)}K&&K.mrChange();u=__PH.cookie.s.getGlobal("a")||mr.cookie("loginS");t.checked="string"!==typeof u||"1"===u;t.mrChange();G.emit("reset",a);mr.removeClass(document.body,"status__user_hasAuth");
mr.addClass(document.body,"status__user_hasNoAuth")}!a.HasAuth&&!a.User?mr.addClass(document.body,"status__user_hasNoAuth_noCookie"):mr.removeClass(document.body,"status__user_hasNoAuth_noCookie");y=a}});var u=mr.id("password_warning"),A=new Splash.Hint("",u);A.on("show",function(){mr.counter("d721322")});G.on("switch",A.hide);G.on("reset",function(){s.value||(A.hide(),u.style.display="none")});new function(){this.input=s;this.allowedSymbols=/^[0-9a-zA-Z!@#$%^&*()\-<>'"_+=;:,./?\\|`~[\]{}]+$/i;this.wrongAlpha=
/[\u0430-\u044f\u0410-\u042f\u0454\u0457\u0491\u0456]/i;this.wrongSymbolsMsg="\u0412\u044b \u0432\u0432\u0435\u043b\u0438<br/>\u043d\u0435\u0434\u043e\u043f\u0443\u0441\u0442\u0438\u043c\u044b\u0435 \u0441\u0438\u043c\u0432\u043e\u043b\u044b";this.wrongBadLangMsg="\u0421\u043c\u0435\u043d\u0438\u0442\u0435 \u0440\u0430\u0441\u043a\u043b\u0430\u0434\u043a\u0443";this.warningEvent=new Splash.DOMEvent(this.input,"keyup",mr.proxy(function(){this.input.value&&!this.allowedSymbols.test(this.input.value)?
(this.wrongAlpha.test(this.input.value)?A.setContent(this.wrongBadLangMsg):A.setContent(this.wrongSymbolsMsg),u.style.display="block",mr.counter("d755623")):(A.hide(),u.style.display="none")},this));this.warningEvent.attach()};var V=!1,na=new Splash.DOMEvent(document,"keyup",function(a){27==a.which&&(na.detach(),V=!1)});window.Splash.mailboxDoCount=function(){if(V)return!1;na.attach();return V=!0}})();
(function(){var a=mr.id("js-my-messages");mr.id("js-my-messages-link");var b=mr.id("js-my-messages-icon"),c=mr.id("js-my-friendships"),f=mr.id("js-my-friendships-link"),d=mr.id("js-my-friendships-icon");window.Splash.ajaxUpdates.push({data:"my",cb:function(h){h.HasMy?(a.innerHTML=h.MyMessages_cnt?h.MyMessages_cnt+" "+_plural(h.MyMessages_cnt,Splash.data.my.messages[0]):Splash.data.my.messages[1],c.innerHTML=h.MyFriendships_cnt?h.MyFriendships_cnt+" "+_plural(h.MyFriendships_cnt,Splash.data.my.friendships[0])+
Splash.data.my.friendships[1]:Splash.data.my.friendships[2],f.href=f.href.split("?")[0]+"?from=splash&requests="+h.MyFriendships_cnt+"#notify=people",mr["0"==h.MyMessages_cnt?"removeClass":"addClass"](b,"icon_counter_my-messages_unread"),mr["0"==h.MyFriendships_cnt?"removeClass":"addClass"](d,"icon_counter_my-friendship_unread"),mr.removeClass(document.body,"status__user_hasNoMy"),mr.addClass(document.body,"status__user_hasMy")):(mr.removeClass(document.body,"status__user_hasMy"),mr.addClass(document.body,
"status__user_hasNoMy"))}})})();
mr.mraSuggest&&function(a){function b(a){if(!f){clearTimeout(d);mr.counter("d929045");var b=mr.id("mraSuggest"),c=mr.id("mraTitle"),q=mr.id("mraDescription"),p=a.items&&a.items.length;try{if("ok"===a.status&&0!=p){for(var w=0;w<p;w++){var K=a.items[w],s=document.createElement("a"),t="http://agent.mail.ru/friends?partnerid=ava",B=1==p?"\u0443\u0436\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0435\u0442":"\u0443\u0436\u0435 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u044e\u0442";s.className=
"social_mra__suggest__avatars__image";s.href=t;s.style.backgroundImage="url(//avt.foto.mail.ru/"+K.photoBox+"/_avatar22)";s.title=K.nick;s.name="clb877223";b.appendChild(s)}q.innerHTML=B;q.href=t;q.name="clb877221";c.href=t;c.name="clb877221";b.style.visibility="visible";mr.counter("d876981")}else"ok"===a.status&&0==p?mr.counter("d876980"):mr.counter("d876974")}catch(y){window.logError&&logError(y,"createMraSuggests"),mr.counter("d929044")}q.style.visibility="visible";f=!0}}function c(){d=setTimeout(function(){b({status:"error"})},
750);mr.getScript("//mrimraker1.mail.ru/agent_suggest?json=1&callback=getMraFriends",!1,"utf-8")}var f=!1,d;a.getMraFriends=function(a){b(a)};"opera"in a?a.addEventListener("DOMContentLoaded",function(){c()},!1):c()}(window,document);
(function(){var a=0;window.reloadSlots=function(b,c){return function(){var f="reloadSlots"+a++;window[f]=function(a){try{var b=a.length,c,d,f,h;for(c=0;c<b;c++){d=a[c].slot;var s=a[c].html,t=a[c].slot||"",B="u"+t+(new Date).getTime()*parseInt(1E5*Math.random()),s=s.replace(/(<script[^>]*>)\s*(<\!--|\/\/\s*<!\[CDATA\[)/gi,"$1;").replace(/\/\/\s*(--\>|\]\]>)\s*(<\/script>)/gi,";$2");f=s="<script>window.qwe"+B+t+' = "";<\/script>'+s.replace(/\w+\.write(ln)?\(/ig,"qwe"+B+t+"+=(").replace(/<noscript>/ig,
"<\!--").replace(/<\/noscript>/ig,"--\>")+'<span id="'+B+t+'"></span><script>mr.id("'+B+t+'").innerHTML = "<i style=\'display:none;\'>&nbsp;</i>" + qwe'+B+t+";<\/script>";h=mr.id("slot_"+d);h.innerHTML='<i style="display:none;">&nbsp;</i>'+f;setTimeout(function(a){return function(){try{for(var b=a.getElementsByTagName("script");b.length;){script=b[0];script.parentNode&&script.parentNode.removeChild(script);var c=script,d=c.text||c.textContent||c.innerHTML||"",e=document.getElementsByTagName("head")[0]||
document.documentElement,f=document.createElement("script");f.type="text/javascript";if(c.src)f.setAttribute("src",c.src+"?rnd="+Math.random());else try{f.appendChild(document.createTextNode(d))}catch(h){f.text=d}e.insertBefore(f,e.firstChild);e.removeChild(f)}}catch(p){window.logError&&logError(p,"execInnerScripts")}}}(h),0)}}catch(y){window.logError&&logError(y,"reloadSlots")}};setTimeout(function(){window[f]=function(){}},6E4);var d=[];if(c)for(var h in c)c.hasOwnProperty(h)&&d.push([h,c[h]].join("="));
h="//ad.mail.ru/adq/?callback="+f+"&q="+b.join("&q=");_EXPERIMENTID&&(h+="&test_id="+_EXPERIMENTID);_PREVIEW&&(h+="&preview="+_PREVIEW);d.length&&(h+="&"+d.join("&"));mr.getScript(h,!1,"utf-8")}}})();
(function(){function a(a,d){f=d;var e=c+(window.__PH&&a.data&&a.data.email?"&Login="+encodeURIComponent(a.data.email):"")+"&rnd="+(new Date).getTime()+Math.random();percent(mr.LF1Percent)&&((new Image).src=mr.getLf1Url({zero:1},e));mr.getJson(e,{},b);return!1}function b(a){try{if(a)for(var b=0,c=window.Splash.ajaxUpdates.length;b<c;b++){var d=window.Splash.ajaxUpdates[b];d.cb(d.data?a[d.data]:a)}}catch(e){window.logError&&logError(e,"getSplash")}"function"===typeof f&&f()}var c=location.href.split("#")[0].split("?")[0]+
"?json=1",f=function(){};if(__mailUpdated)__mailUpdated=!0,__PH.on("update",function(b,c){a(b,c)});else __PH.once("update",function(b,c){__mailUpdated=!0;__PH.on("update",function(b,c){a(b,c)});c()});__PH.on("authChange",function(b,c){a(b,c);d()});var d=reloadSlots([4015,217,4499]);if(mr.onFocusBannerReload){var h=!1;__PH.on("visibilitychange",function(a){a.data.visible&&h&&(e(),d(),mr.counter("d1464827"))});var e=function(){h=!1;setTimeout(function(){h=!0},6E5)};e()}})();
(function(){mr.cookie("newsT",null);window.newsTabs=new Splash.News(mr.id("news"),{tabs:{containerClass:"news__tabs",tabClass:"news__tabs__item",tabActiveClass:"news__tabs__item_selected",doubleTabClass:"news__tabs__item_double",tabLinkClass:"news__tabs__item__link",moreId:"news__more",moreIconId:"news__more__icon",moreDropdownId:"news__more__dropdown",moreOpenedClass:"news__tabs__more_opened",moreSelectedClass:"news__tabs__more_selected",moreDropdownItemClass:"news__tabs__more__dropdown__item",moreDropdownItemSelectedClass:"news__tabs__more__dropdown__item_selected",
moreDropdownItemLinkClass:"news__tabs__more__dropdown__item__link"},content:{containerId:"news__wrap",tabClass:"news__list",slotClass:"news__list__slot"},mask:{maskId:"news__mask"}});window.newsTabs.on("loaded",function(){var a;window.newsTabs.on("tab:activate",function(){clearTimeout(a);a=setTimeout(function(){mr.updateTGB&&(mr.counter("d1653700"),b())},100)});setTimeout(function(){mr.updateTGB=!1},2592E5);var b=reloadSlots([4847],{bv:mr.blockVersions.textBannerVersion})})})();
function splashMultiAuthInit(){mr.isMultiAuth="isMultiAuth"in __PH&&!0===__PH.isMultiAuth();if(mr.isMultiAuth){mr.multiuser=mr.id("MA_user-email");var a=Splash,b=function(b){mr.hasClass(e,k)&&(clearTimeout(q),mr.removeClass(e,k),e.style.width="",a.DOMEvent.removeListener(document,"click",c),b&&b.preventDefault())},c=function(a){var c;mr.hasParent(a.target,e)?(c=mr.hasParent(a.target,"js-logout")||mr.hasClass(a.target,"js-logout")&&(c=a.target))?(__PH.logoutAccount(mr.hasParent(c,"js-list-user").getAttribute("data-email"),
f),mr.counter("clb1199007"),a.preventDefault()):(c=mr.hasParent(a.target,"js-list-user")||mr.hasClass(a.target,"js-list-user")&&(c=a.target))?(__PH.switchAccount(c.getAttribute("data-email")),mr.counter("clb1195611"),a.preventDefault(),b()):mr.hasParent(a.target,"js-button")||mr.hasClass(a.target,"js-button")&&a.target?(a.preventDefault(),b()):mr.hasParent(a.target,"js-login")||mr.hasClass(a.target,"js-login")&&a.target?(mr.counter("clb1195612"),b(),mr.isPHAuthForm&&(a.preventDefault(),__PH.authForm.show())):
mr.isNode(a.target)&&"a"===a.target.tagName.toLowerCase()&&b():b()},f=function(a){var b=mr.id("multiAuthMenuList");if("error"!==a.status){a=a.accounts;1<a.length?(mr.addClass(e,"multiauth__menu_multi"),4<a.length?mr.addClass(e,"multiauth__menu_limit"):mr.removeClass(e,"multiauth__menu_limit")):(mr.removeClass(e,"multiauth__menu_multi"),mr.removeClass(e,"multiauth__menu_limit"));for(var c=[],d=0,f=a.length;d<f;d++){var h="",k=a[d];0===d?h=" multiauth__menu__dropdown__list__item_first":d===a.length&&
(h=" multiauth__menu__dropdown__list__item_last");k.active&&(h+=" multiauth__menu__dropdown__list__item_current");var q=k.counters&&k.counters.mail;c.push("<div"+(!k.active?' tabindex="0"':"")+' class="multiauth__menu__dropdown__list__item'+(!k.active?" js-list-user":"")+h+'" data-email="'+k.email+'" onkeypress="if ((event.which || event.charCode || event.keyCode) === 13){var t = (event.target || event.srcElement); t.nodeType == 3 && (t = t.parentNode); t.click();}"><div class="multiauth__menu__dropdown__list__item__avatar" style="background-image:url(//filin.mail.ru/pic?from=splash&email='+
k.email+'&width=45&height=45);"></div><div class="multiauth__menu__dropdown__list__item__info"><div class="multiauth__menu__dropdown__list__item__info__email">'+(!k.active?'<div class="multiauth__menu__dropdown__list__item__info__email__counter'+(q?" multiauth__menu__dropdown__list__item__info__email__counter_visible":"")+'"><i class="multiauth__menu__dropdown__list__item__info__email__counter__icon"></i><span class="multiauth__menu__dropdown__list__item__info__email__counter__text">'+q+"</span></div>":
"")+'<div class="multiauth__menu__dropdown__list__item__info__email__text">'+k.email+'</div></div><div class="multiauth__menu__dropdown__list__item__info__text">'+(k.firstName&&k.lastName?k.firstName+" "+k.lastName:"")+'</div></div><div class="multiauth__menu__dropdown__list__item__logout js-logout"><span class="portal-button portal-button_only-icon"><span class="portal-button__fake"><span class="portal-button__fake__icon portal-button__fake__icon_multiauth portal-button__fake__icon_multiauth_exit"></span></span></span></div></div>')}b.innerHTML=
c.join("")}},d=mr.id("js-mailbox-user"),h=mr.id("js-mailbox-user-wrap"),e=mr.id("multiAuthMenu"),k="multiauth__menu_open";mr.id("multiAuthHolder").appendChild(e);mr.addClass(h,"w-mailbox__userinfo__email_multiauth");a.DOMEvent.on(d,"click",function(d){if(mr.hasClass(e,k))b(d);else if(!mr.hasClass(e,k)){var h=function(){q&&(mr.addClass(e,k),a.DOMEvent.on(document,"click",c),q=!1)},q=!0,s;mr.addClass(e,"multiauth__menu__dropdown_loading");mr.removeClass(e,"multiauth__menu__dropdown_error");s=setTimeout(h,
100);__PH.loadAccountsList(function(a){clearTimeout(s);"timeout"===a.status||"error"===a.status?(mr.removeClass(e,"multiauth__menu__dropdown_loading"),mr.addClass(e,"multiauth__menu__dropdown_error")):(f(a),mr.removeClass(e,"multiauth__menu__dropdown_loading"));h();e.style.width=e.offsetWidth+"px"});mr.counter("clb1195610");d&&d.preventDefault()}});a.DOMEvent.on(e,"mouseover",function(){clearTimeout(q)});a.DOMEvent.on(e,"mouseout",function(){clearTimeout(q);q=setTimeout(b,4E3)});var q}}
splashRadar("JSInit",1);splashRadar._JSINITTime=(new Date).getTime()-splashRadar._JSINITTime;
